### ISSUE TITLE
polmineR::dispersion: count zeroes

### ISSUE THREAD

**Issue by novacellus** [PolMine/polmineR#104]
Would it possible that the polmineR::dispersion() yield 0 when there's no occurrence of a term in the structural unit (in addition to positive counts that it returns now)? There is obviously a way to do this (for example, one can merge dispersion() results with that of size() function), but it would be so much easier if done through an option to dispersion(). Among many uses of this statistics, many dispersion measures rely on zero counts, so this would be a major enhancement.

**Comment by ablaette** [comment]
Thank you so much for raising this issue. It is quite cdlear that you are perfectly right. The `dispersion()` should return zeros as the methods' default behaviour.

It takes some care to implement this in a way that keeps the performance cost minimal and to expand the `data.table` with results with zero values if necessary. A reworked `dispersion()`-method for `corpus` objects  / corpora specifief by a length-one character vector now reports zeros. Get the new polmineR version (v0.7.11.46) from the development branch (`devtools::install_github("PolMine/polmineR", ref = "dev"). 

The next step will be to address the `dispersion()`-method for `partition`/`subcorpus`/`slice` objects. The way it should work is quite clear if you supply one s_attribute (report results, including zeros, for all values of the s-attribute in the partition/subcorpus/slice).  But if you go for the dispersion (i.e. crosstabulation for two s-attributes, should zero values be reported for all values in the corpus, or only for the values in the partition. This question may sound somewhat opaque, bit it has kept me from immediate implementation.

**Comment by ablaette** [comment]
I think I found a way to implement the `dispersion()`-method for `partition` or `subcorpus` objects in a parsimonious manner. Results including zero matches are reported now (i.e. new development version on the dev branch) for all values of the s-attribute occurring in the `subcorpus`/`partition`-object. Please let me know whether you think everything works in a plausible manner now.

**Comment by PolMine** [comment]
A concluding example upon closing this issue, as a check that including zero matches in the results of `dispersion()` works.

```r
library(polmineR)
dispersion("GERMAPARLMINI", query = "Integration", s_attribute = "date")
```
