### ISSUE TITLE
Error in kwic if cpos = FALSE 

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#106]
There are two ways the  KWIC method doesn't behave as expected when cpos is set to false.

### Scenario A: Simple KWIC query:

`
kwic_out <- kwic("GERMAPARL", query = "Klimakrise", cpos = FALSE)
`

In this case, the output is an empty table.

### Scenario B: KWIC with metadata. 

`
kwic_out <- kwic("GERMAPARL", query = "Klimakrise", meta = c("speaker", "date"), cpos = FALSE)
`

Here, an actual error occurs: 
> Error in eval(bysub, x, parent.frame()) : object 'match_id' not found 

In addition, there is a typo in the documentation. Describing the cpos parameter there is "if the hits" when it should be "of the hits".

**Comment by PolMine** [comment]
The argument `cpos` is more dangerous than I had thought... A slight rework of the `kwic()` method makes the method more robust. The issue/error you came across will not occurr.

The sense of the argument is to minimize object size, if memory is limited (e.g. if you compute MANY kwic objects).  It should be handled with care, and sticking to the default value `TRUE` will usually make sense. To explain the usage of the argument, I have expanded the documentation. Now it says:

"Logical, if TRUE, a data.table with the corpus positions ("cpos") of the hits and their surrounding context will be assigned to the slot "cpos" of the kwic-object that is returned. Defaults to TRUE, as the availability of the cpos-data.table will often be a prerequisite for further operations on the kwic object. Omitting the table may however be useful to minimize memory consumption."

**Comment by ChristophLeonhardt** [comment]
The documentation certainly makes things more clear. I am not sure why I wanted to omit the cpos table, but indeed the errors don't occur anymore after updating to the latest version, so thank you very much.
