### ISSUE TITLE
Shiny | Feature Request: Show code

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#107]
When working with the `polmineR()`shiny environment, it would be nice to be able to see the code which is running in the background while pressing buttons etc., either as in the build-in shiny showcase display mode (https://shiny.rstudio.com/articles/display-modes.html) or as an extra feature to print a script. This could help reproducibility of analyses performed within the shiny environment and facilitate the acquisition of coding skills. 

Credit and thanks to the workshop participant who proposed this.

**Comment by PolMine** [comment]
A new polmineR version available at the dev branch (just for counting at this stage) includes a preliminary implementation of displaying the code for what is done via the GUI. Would be great to get your feedback.

**Comment by ChristophLeonhardt** [comment]
I think this is a nice implementation. Right now I cannot think of anything else that could be done.

**Comment by PolMine** [comment]
Displaying the code is now possible for all core methods, and I added code highlighting to make it look nice and easy to read.
