### ISSUE TITLE
Error when enriching a KWIC object previously stored and then loaded as an RDS file

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#108]
I did find a very peculiar problem which is unlikely to cause major problems for most people. 

If I save a KWIC object as an RDS file, load the same RDS file again and try to enrich the object, it won't work with the error message being:

>  Error in colnamesInt(x, neworder, check_dups = TRUE) : 
>   argument specifying columns specify non existing column(s): cols[1]='year'  

This is because although the rest of the `enrich` method does work, the line 

`
.Object@stat[, (s_attr) := as.nativeEnc(struc_values, from = .Object@encoding)]
`

doesn't add the s_attribute to the stat data.table. I can only assume that the encoding of the object changes when storing it as an rds object and thus the strucs of the corpus and the encoding of the object differ. However, both the UNGA corpus and the locale are UTF-8. It is very specific and a bit strange.

Here is a reproducible example:

```
library(polmineR) # polmineR_0.7.11.9049
use("UNGA")
unga_sanctions_kwic <- kwic("UNGA", "sanctions")
saveRDS(unga_sanctions_kwic, "unga_sanctions_kwic.rds")
unga_sanctions_kwic <- readRDS("unga_sanctions_kwic.rds")
unga_sanctions_kwic_enriched <- enrich(unga_sanctions_kwic, s_attributes = "year")
```

One workaround is the less data.table-esque way to assign the additional year variable like this instead of the line above:

`
.Object@stat[[s_attr]] <- as.nativeEnc(struc_values, from = .Object@encoding)
`

**Comment by PolMine** [comment]
Saving and loading `kwic` objects, or `textstat` objects in general seems to be tricky.  You are quite right that it is obviously an issue with the `data.table` in the `stat`slot. Using `readRDS()` to restore a `data.table` has been discussed [here](https://stackoverflow.com/questions/37231675/r-data-table-and-saverds) and [here](https://stackoverflow.com/questions/31250999/r-readrds-load-fail-to-give-identical-data-tables-as-the-original). 

As you can see from the following simplified code you offered, the reloaded `data.table` has an odd externalptr:

```r
library(polmineR)
use("UNGA")
k1 <- kwic("UNGA", "sanctions")
temp_kwicfile <- tempfile()
saveRDS(k1, file = temp_kwicfile)
k2 <- readRDS(file = temp_kwicfile)
attr(k2@stat, ".internal.selfref")
```

It is restored as soon as we copy the `data.table`, and then enriching works.

```r
k2@stat <- copy(k2@stat)
attr(k2@stat, ".internal.selfref")
k2_enriched <- enrich(k2, s_attributes = "year")
```

The finding that copying the `data.table` does the trick explains why the possible solution you identified ... 

```r
.Object@stat[[s_attr]] <- as.nativeEnc(struc_values, from = .Object@encoding)
```
... makes the code work: This kind of assignment provokes copying the `data.table`, and this is why I try to avoid this kind of assignment wherever I can.

A "pure" `saveRDS()` approach for `textstat` objects seems to be a problem. One potential solution would be to define methods for saving and loading `textstat` objects, which will perform the copying of the `data.table` internally. Indeed, there is a `store` method in the package that I would like to get rid of in its current form (saving Excel files). Then we could have robust `store()` and `restore()` methods in the package.

**Comment by ChristophLeonhardt** [comment]
This is quite interesting indeed. It is certainly true that copying the entire data.table should be avoided. And while it is great to have the possibility to export spreadsheets - I think, most users do appreciate this - being able to store large `textstat` objects such as large `kwic` objects not just as spreadsheets but as objects seems very useful to me as well.

**Comment by PolMine** [comment]
To restore S4 objects with a `data.table` in any slot, I drafted this auxiliary function.

```r
restore <- function(filename){
  y <- readRDS(file = filename)
  if (isS4(y)){
    all_slots <- getSlots(class(y))
    dt_slots <- names(y_slots[which(y_slots == "data.table")])
    if (length(dt_slots) > 0L){
      for (slot in dt_slots) slot(object = y, name = slot) <- copy(slot(y, slot))
    }
  }
  y
}
```

This is the code I used for testing.

```r
k <- kwic("REUTERS", query = "oil")
kwicfile <- tempfile()
saveRDS(k, file = kwicfile)
k <- restore(filename = kwicfile)
enrich(k, s_attribute = "id")
```

It seems to work - the issue we seems to be gone. As you know, I like to avoid copying a `data.table`, but it seems to work.

**Comment by PolMine** [comment]
I failed to mention that the new `restore()`-method is included in polmineR v0.8.0.9015, available at the dev branch. Looking forward to your feedback!

**Comment by ChristophLeonhardt** [comment]
This works nicely on rds objects as it is shown here and in the documentation of `restore()`. So thank you for that! It does solve the problem at hand.

 Maybe it is worth mentioning that it does not work when the object is stored via `save()` (i.e. as an RData object?). So maybe the recommendation to store these objects as rds would prevent some headache for some users who would chose `save()` otherwise?

**Comment by ablaette** [comment]
The scenario that an object is loaded using `load()` as quite common: That will be the case whenever you save the objects of a session after `q()`. So I turned the `restore()`-function into a `restore()`-method that works on `textstat` objects apart from providing a filename. Have written some documentation. Unit test still missing.
