### ISSUE TITLE
cooccurrence function ignores s_attribute

### ISSUE THREAD

**Issue by ausgerechnet** [PolMine/polmineR#118]
When calculating the co-occurrence counts of a CQP query via `cooccurrences()`, the `s_attribute` parameter is – as far as I can see – ignored. Here's an example using the GermaParl corpus and the `speaker` attribute:

```
library(polmineR)
library(GermaParl)
use("GermaParl")
cooc <- cooccurrences("GERMAPARL", query='[word="Sehr"] [word="geehrte"]', left=5, right=5, p_attribute='lemma')
format(cooc)[cooc.f$lemma == "Wort", 'count_coi']
cooc <- cooccurrences("GERMAPARL", query='[word="Sehr"] [word="geehrte"]', left=5, right=5, p_attribute='lemma', s_attribute='speaker')
format(cooc)[cooc.f$lemma == "Wort", 'count_coi']
cooc <- cooccurrences("GERMAPARL", query='[word="Sehr"] [word="geehrte"]', left=5, right=5, p_attribute='lemma', s_attribute='foobar')
format(cooc)[cooc.f$lemma == "Wort", 'count_coi']
```

The first two should clearly yield different results, the third one should throw an error, cf. `kwic()`:

```
kwic("GERMAPARL", 'MU(meet [word = "geehrte"] [lemma="Wort"] -5 5);', s_attributes='speaker')
kwic("GERMAPARL", 'MU(meet [word = "geehrte"] [lemma="Wort"] -5 5);', s_attributes='foobar')
```

However, all three of them yield a count of 490.

**Comment by PolMine** [comment]
Thanks a lot for sharing this observation. The functionality to remove tokens in the context
of a query match that transgress the change of a s-attribute from the context is there. But
is poorly exposed and implemented.

The `context()`-method, the worker behind the `kwic()`- and the `cooccurrences()`-method has
an argument `boundary` argument that takes an s-attribute that will check tokens in the query
context whether they are within or beyond a struc.

The `kwic()`-method can pass the `boundary` argument to a `context()`-call via the three 
dots `...`, but the `cooccurrences()`-method does not have the three dots. Yet to use the 
check for boundaries for cooccurrences, you can call the `context()`-method first, and continue
with a `cooccurrences()`-method call. See the following examples.

In the examples I use the typical concluding words of a speech as a query which typically 
occurs before a speaker changes.

```r
library(polmineR)

conc_min_1 <- corpus("GERMAPARLMINI") %>%
  kwic(query = '"Herzlichen" "Dank"', boundary = "speaker", cqp = TRUE) # works

conc_min_2 <- corpus("GERMAPARLMINI") %>%
  context(query = '"Herzlichen" "Dank"', cqp = TRUE, boundary = "speaker") %>%
  kwic()

cooc_min <- corpus("GERMAPARLMINI") %>%
  context(query = '"Herzlichen" "Dank"', cqp = TRUE, boundary = "speaker") %>%
  cooccurrences()
```

So it is quite clear that `kwic()` and `cooccurrences()` (just) need to expose the `boundary`
argument explicitly. 

An alternative naming would be an argument `s-attribute` for the boundary checking. But that 
provokes the problem that the `kwic()`-method has an `s-attribute` argument for the metadata
that is displayed. 

What needs to be implemented and documented is fairly clear. My question is whether the naming of the `boundary` argument is sufficiently clear?

**Comment by ausgerechnet** [comment]
In my opinion (and in my own [python implementation](https://github.com/ausgerechnet/cwb-ccc)), these are clearly two different parameters and neither of the them should be named `s_attribute` (instead say `s_meta` and `s_boundary`).

In polmineR version 0.8.0, `?cooccurrences` yields the following description for the parameter `s_attribute`:

> If provided, it will be checked that corpus positions of windows do not extend beyond the region defined by the s-attribute.

… which it clearly doesn't.

Naming any one of the parameters `s_attribute` will inevitably lead to confusion at some point or another.

**Comment by PolMine** [comment]
Quite clearly, the argument `s_attribute` including the documentation have gone out of touch with what the `context()` method does. As I think that the argument `boundary` describes and does quite well what you were looking for, I mapped `cooccurrences()` on the `context()`-method (i.e. argument `s_attribute` has been renamed). Before closing the issue, I would just like to add a unit test, to ensure that nothing can go wrong with boundary checking in the future.
