### ISSUE TITLE
kwic()-method fails for cooccurrrences-object if more than one p-attribute was used

### ISSUE THREAD

**Issue by ablaette** [PolMine/polmineR#119]
I hope the headline is sufficiently telling to describe the problem I have come across. See this example:

```r
x <- corpus("GERMAPARLMINI") %>%
   cooccurrences(query = '"[eE]urop.*"', cqp = TRUE, p_attribute = c("word", "pos")) %>%
   subset(pos == "NN") %>% 
   subset(count_coi >= 3L) %>%
   subset(ll >= 10.83)
```
This is results in a `cooccurrences` object. It is possible to apply the `kwic` method on it, which is defined for the `context` class (the `kwic`-class inherits from it). But this fails:

```r
kwic(x)
```
The error you see is "Fehler in .subset2(x, i, exact = exact) : Indizierung außerhalb der Grenzen".

My analysis is that this is that the error occurs when a rudimentary `kwic` object is enriched, i.e. this line of the `enrich()`-method for `kwic` objects:

```r
.fn <- function(.SD) paste(.SD[[.Object@p_attribute]], collapse = " ")
table_ext <- .Object@cpos[, .fn(.SD), by = c("match_id", "direction"), with = TRUE]
```
Just as a cross-check - this works:

```r
x <- corpus("GERMAPARLMINI") %>%
  cooccurrences(query = '"[eE]urop.*"', cqp = TRUE, p_attribute = c("word")) %>%
  subset(count_coi >= 3L) %>%
  subset(ll >= 10.83) %>%
  kwic()
```

**Comment by PolMine** [comment]
Indexing `cooccurrences` objects based on more than one p-attribute will work now. The p-attribute used tó reconstruct the text is now the first p-attribute, if there is more than one. The line identified before is modified slightly:

```r
.fn <- function(.SD) paste(.SD[[.Object@p_attribute[1]]], collapse = " ")
```
