### ISSUE TITLE
ngrams error

### ISSUE THREAD

**Issue by hsang** [PolMine/polmineR#12]
Hi all,

First of all, thank you for deveoping polmineR, I think it is fantastic. I have a problem, maybe it is because I do something wrong. When I try to get ngrams from a object of class partition I receive this message:

_Error in names(idList)[j] <- paste("id_", i, "_", pAttr, sep = "") :    'names[1]' attribute must be the same length as the vector[0]_

I use this command: _ngrams(example, n = 2, pAttribute = "word",  char = NULL, progress = FALSE)_

Thank you for your help.

Best,
Hugo

**Comment by ablaette** [comment]
Dear Hugo,

thanks for raising the issue! I have just pushed a bug fix to the dev branch. 

The documentation of the method now includes a short sample for using the method to count n-grams based on tokens. Another usage is to count n-grams based on characters, a functionality I use for duplicate detection in the Duplicates class in the polmineR.misc package.

Please let me know whether everything works for you now!

Kind regards
Andreas

**Comment by hsang** [comment]
Dear Andreas,

it works like a charm now. Thank you very much.

Best,
Hugo
