### ISSUE TITLE
as.phrases from ngram | check if cqp-expression is legal

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#123]
Generating phrases from ngrams can throw warnings because the CQP query created is not checked before. 

Here is the according part in the phrases.R

```
  queries <- do.call(sprintf, args)
  regions_matrix <- cpos(.Object@corpus, query = queries,  cqp = TRUE, ...)
```

This is the case in particular when it comes to parentheses as the following example illustrates. 

```
library(polmineR)
use("GermaParl")
germaparl_phrases <- ngrams("GERMAPARL", p_attribute = "word", n = 2L) %>%
  pmi(observed = count("GERMAPARL", p_attribute = "word")) %>%
  subset(ngram_count >= 5L) %>%
  subset(152830:152890) %>%
  as.phrases()
```

**Comment by PolMine** [comment]
To check the validity of CQP queries, I have expanded the checks in the `check_cqp_query()` function. It will now consider whether the number of opening and closing brackets is identical. Queries that do not meet this condition are left out from the generation of phrases (to avoid an outright error). You get a warning that includes the buggy query.

**Comment by ChristophLeonhardt** [comment]
These warnings are expressive and seem to solve the problem of the scary cqp warnings. Feel free to close. Thanks!
