### ISSUE TITLE
Using DataTables Buttons extensions

### ISSUE THREAD

**Issue by PolMine** [PolMine/polmineR#125]
On a new temporary branch calles "buttons", I have started to experimentally use the Buttons extension of the DataTables JavaScript library that is exposed in R via the `DT` package and the `DT::datatables()` function. 

Using the Buttons extension, some buttons (here: "Copy", "CSV", "Excel", "PDF", and "Print" ) are displayed above a table, exposing the denoted export options. Use the following snippet to get a quick expression:

```r
library(polmineR)
corpus("GERMAPARLMINI") %>% cooccurrences(query = "Integration") %>% as("htmlwidget")
```

Modifying the code to use the buttons is not difficult. This is the (modified) coerce method to generate a DataTable from a `coocurrences` object:

```r
setAs(from = "cooccurrences", to = "htmlwidget", def = function(from){
  dt <- copy(round(from)@stat)
  colnames(dt) <- gsub("count_", "n_", colnames(dt))
  DT::datatable(
    dt,
    extensions = "Buttons",
    options = c(list(
      pageLength = getOption("polmineR.pagelength"),
      lengthChange = FALSE
      ),
      if (interactive()){
        list(
          dom = 'Bfrtip',
          buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
        )
      } else NULL
    ),
    rownames = FALSE
  )
})
```

Using the buttons extension throughout will require some careful thought. In this preliminary implementation, I thought that buttons are useful in an interactive session, but should not be there by default when you include a table in a Rmarkdown document. This is addressed in the draft code, but it would be more flexible to move decisions about buttons to options that may be reset according to users' needs.

One beauty of the buttons is the flexibility and strong intuitive appeal. From a more technical point, I dream about dropping the current export functionality of the package (`mail()`-method) that is not easy to use. Neither in an interactive R session, nor in the shiny app.

Before proceeding, I would glad to receive feedback!

**Comment by PolMine** [comment]
Initially, some buttons ("Excel", "CSV") did not work as intended. Updating to the latest RStudio version solved the issue. It might make sense to check for the RStudio Version using  `rstudioapi::versionInfo()[["version"]]`. The "Print" still does not work. But as you prepare a PDF, printing is possible, so I will drop this button.

**Comment by ChristophLeonhardt** [comment]
I just had a look at it and I have to say: Having these buttons is very convenient and could be very useful for the shiny app in particular. Making them optional in the html output would be a plus.

**Comment by PolMine** [comment]
The max length of the table is now 250, which does not cause a substantial problem. Having implemented the buttons throughout ... would be glad to get feedback!

**Comment by ChristophLeonhardt** [comment]
It is certainly a good idea to limit the length of the table. However, at the moment I cannot see where this length is set and documented? I can imagine that this limitation can be confusing when someone wants to export a larger table and isn't aware that this limit is set. That's why the documentation should be explicit. Other than that I still think that this is a very nice feature.

In addition: When clicking on "copy", a message appears stating "copied X rows to clipboard" whereas X can be larger than 250 while the number of rows which have actually been copied is 250. The message should say 250 as well, I guess.
