### ISSUE TITLE
Cannot use the GermaParl package after update to 0.8.0.9011

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#127]
Here, it is arguable if this is an issue of the `polmineR` or the `GermaParl` package but since it is possible that other packages are affected by this as well, I post it here:

After updating to `0.8.0.9011` (and probably also on the version before that) I am not able to use the functionalities of the GermaParl package anymore: 

```
GermaParl::germaparl_download_corpus()
```
 
> Error: object ‘Corpus’ is not exported by 'namespace:polmineR' 

I assume that this error message gives it away, although I don't see right away where these changes were made.

**Comment by PolMine** [comment]
I had hoped that I could finally get rid of the deprecated `Corpus` class. But the first step is apparantly that I remove the usage of the class in the GermaParl package... So I have re-introduced the class grudgingly, and for the time being. Thanks for your attention!
