### ISSUE TITLE
polmineR now dependent on R >= 3.5.0?

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#129]
Just a small observation: Apparently, the `polmineR` package now needs `isFALSE` which was introduced in base R in version 3.5. When calling the `use()` function in earlier versions of R, it is reported that `isFALSE` is an unknown function. This probably doesn't really concern anyone, but maybe it is useful to clarify the R version in the DESCRIPTION file?

**Comment by ablaette** [comment]
This is a very helpful observation. I added "Depends: R (>= 3.5.0)" to the DESCRIPTION.

Actually, I could imagine very well that people may still be using older R versions. But I think the beauty of using `isFALSE()` is that it makes the code easier to read, in the sense of literate programming.
