### ISSUE TITLE
Improve performance of decoding entire p-attributes

### ISSUE THREAD

**Issue by PolMine** [PolMine/polmineR#130]
The performance of decoding the token stream for a p-attribute is not quite satisfactory and has started to annoy me. It's one of the occasions when you may sit around before your machine for almost a minute!

So I had started to experiment with parallelizing the C++ code to decode p-attributes in the RcppCWB package using OpenMP. But there is no performance gain at all. My interpretation is that accessing corpus data on disk (i.e. I/O operations) is the bottleneck, not computation, so parallelization leads to nothing. 

Reconsidering the problem and running a few tests, I found that turning token ids into the decoded attribute, and adjusting the encoding is the time consuming part. So I mused that reading the lexicon directly from the file in the corpus directory and adjusting the encoding *before* decoding the entire token stream might speed up things. 

This is the code of two functions yielding the same result. The first one implements the idea just sketched, the second one implements the fastest traditional solution I could think of (`cl_cpos2str` is somewhat faster than chaining `cl_cpos2id()` and `cl_id2str()`, and `stringi::stri_encode()` beats `iconv()` by a third).

```r
library(polmineR)
library(microbenchmark)
use("GermaParl")

p_attribute_decode1 <- function(x, p_attribute){
  obj <- corpus(x)
  lexfile <- file.path(obj@data_dir, sprintf("%s.lexicon", p_attribute), fsep = "/")
  lexicon <- readBin(con = lexfile, what = character(), n = file.info(lexfile)$size)
  Encoding(lexicon) <- obj@encoding
  lexicon <- stringi::stri_encode(lexicon, from = obj@encoding, to = localeToCharset())
  ids <- RcppCWB::cl_cpos2id(corpus = obj@corpus, p_attribute = p_attribute, registry = registry(), cpos = 0L:(size(obj) - 1L))
  lexicon[ids + 1L]
}

p_attribute_decode2 <- function(x, p_attribute){
  y <- RcppCWB::cl_cpos2str(corpus = x, p_attribute = p_attribute, registry = registry(), cpos = 0L:(size(x) - 1L))
  Encoding(y) <- encoding(x)
  stringi::stri_encode(y, from = encoding(x), to = localeToCharset())
}

dec1 <- microbenchmark({ts1 <- p_attribute_decode1("GERMAPARL", "word")}, times = 10)
dec2 <- microbenchmark({ts1 <- p_attribute_decode2("GERMAPARL", "word")}, times = 10)

identical(tokenstream1, tokenstream2)
```

The result is quite clear: `p_attribute_decode1()` is the winner. On my machine, the average time to decode the p_attribute "word" is 13.87 secs, whereas `p_attribute_decode2()` needs an average of 48.90 secs. Again, note that adjusting the encoding is at least as time-consuming as getting the decoded strings. 

How to feed this performance tweak into polmineR is not as obvious as one might think. For decoding the whole token stream for a p-attribute, the approach of `p_attribute_decode1()` is obviously a substantial improvement. However, the situation is much less clear when it's parts of a corpus that are to be decoded. If you just decode a certain part of the corpus, the `p_attribute_decode2()`-approach may well be faster. But how to decide when to proceed which way? Need to think about it.  Thoughts welcome.

**Comment by ablaette** [comment]
Using the lexicon pays off at a much smaller share of the corpus than I would have thought: I would say as a rule of thumb, if more than 5% of a corpus are decoded, using the lexicon-based approach seems to be an efficient alternative. See the following benchmarking exercise.

```r
library(polmineR)
library(microbenchmark)
use("GermaParl")

decode1 <- function(x, p_attribute, share = 1.0){
  obj <- corpus(x)
  lexfile <- file.path(obj@data_dir, sprintf("%s.lexicon", p_attribute), fsep = "/")
  lexicon <- readBin(con = lexfile, what = character(), n = file.info(lexfile)$size)
  Encoding(lexicon) <- obj@encoding
  lexicon <- stringi::stri_encode(lexicon, from = obj@encoding, to = localeToCharset())
  max_cpos <- as.integer(floor((size(obj) - 1L) * share))
  ids <- RcppCWB::cl_cpos2id(corpus = obj@corpus, p_attribute = p_attribute, registry = registry(), cpos = 0L:max_cpos)
  lexicon[ids + 1L]
}

decode2 <- function(x, p_attribute, share = 1.0){
  max_cpos <- as.integer(floor((size(x) - 1L) * share))
  y <- RcppCWB::cl_cpos2str(corpus = x, p_attribute = p_attribute, registry = registry(), cpos = 0L:max_cpos)
  Encoding(y) <- encoding(x)
  stringi::stri_encode(y, from = encoding(x), to = localeToCharset())
}

range <- c(seq(from = 0.01, to = 0.1, by = 0.01), seq(from = 0.2, to = 0.2, by = 0.1))
df <- do.call(rbind, lapply(
  range,
  function(x){
    message("Share of the corpus to decode: ", x)
    message("... benchmarking decode1()")
    mb1 <- microbenchmark(decode1("GERMAPARL", "word", share = x), times = 10)
    message("... benchmarking decode2()")
    mb2 <- microbenchmark(decode2("GERMAPARL", "word", share = x), times = 10)
    data.frame(share = x, avg1 = mean(mb1$time)/1000000000, avg2 = mean(mb2$time)/1000000000)
  }
))

beepr::beep(5)

plot(
  x = df[["share"]], y = df[["avg2"]], type = "n",
  xlim = c(0,max(range)), ylim = c(0, max(df[["avg2"]])),
  xlab = "Share of the corpus decoded", ylab = "time (in seconds)",
  main = "Time to decode token stream"
)
lines(x = df[["share"]], y = df[["avg1"]], lwd = 2, lty = "dashed", col = "red")
lines(x = df[["share"]], y = df[["avg2"]], lwd = 2, lty = "dotdash", col = "blue")
abline(v = 0.05, col = "darkgrey")
legend(
  x = "topleft",
  legend = c("method1", "method2"),
  lty = c("dashed", "dotdash"),
  col = c("red", "blue"),
  lwd = 2
)
```

**Comment by ablaette** [comment]
The `get_token_stream()` method now implements the idea of (optionally) using the lexicon file. It relies on a new `decode()` method for `integer` vectors` written for this purpose. This is the code I used for testing:

```r
library(polmineR)
use("GermaParl")
gparl <- corpus("GERMAPARL")

system.time(y1 <- get_token_stream(gparl, p_attribute = "word", boost = FALSE))
system.time(y2 <- get_token_stream(gparl, p_attribute = "word", boost = TRUE))
```

If `boost` is `TRUE`, the operation takes 12.5 seconds on my machine whereas `boost = FALSE` will take 50 seconds. So I think this is worth the effort. 

The default value for `boost` will now be `NULL`. If it is not set (i.e. `NULL`) the decision whether to access the lexicon file directly will rely on the size of the corpus and the share to be decoded. If the corpus is larger than 10 000 000 tokens and more than 5 percent are to be decoded, this indicates whether to use the lexicon file.

**Comment by PolMine** [comment]
For the time being, the solution is a substantial performance increase. It would be worthwhile to report the approach takeen in a blogpost, but this is another matter, and I close the issue.
