### ISSUE TITLE
read() | issue when meta length = 1?

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#131]
I adapted an example you provide in the documentation  of the `read()` method. While this works as shown there:

```
library(polmineR)
merkel <- partition("GERMAPARLMINI", date = "2009-11-10", speaker = "Merkel", regex = TRUE)
read(merkel, meta = c("speaker", "date"))
```

This doesn't work:

```
library(polmineR)
merkel <- partition("GERMAPARLMINI", date = "2009-11-10", speaker = "Merkel", regex = TRUE)
read(merkel, meta = "speaker")
```

With the error message being:

> Error in metadata[i, ] : subscript out of bounds 

The documentation at least suggests that this should work but I am not sure what the problem here really is.

**Comment by PolMine** [comment]
I just removed the bug, it is solved in a new version at the dev branch. Internally, it results from an inconsistent behavior of the `s_attributes()`-method: The argument `unique` is ineffective when more than one s_attributes is provided (making the `read()`-method work in this case), but it is applied when you try to get the values of only one s-attribute. So this is a new issue I would like to deal with separately.
