### ISSUE TITLE
setting registry to work with own CWB-encoded corpora

### ISSUE THREAD

**Issue by kairelandkuiper** [PolMine/polmineR#132]
Hello!

I ran polmineR using the Germaparl package and was able to get everything running just fine.
I am having trouble with resetting the registry directory to connect with my CWB-encoded corpora. 
I ran Sys.setenv(“/PATH/TO/YOUR/REGISTRY”) before uploading the polmineR package, and then checked it with registry(). The registry is set to the location of the polmineR package rather than the registry directory for my data. After this, I ran corpus() to check whether my corpora were moved to the polmine directory, and the Germaparl mini corpus was the only one available. 

Thanks for the help with this!

**Comment by PolMine** [comment]
I am very well aware that the documentation is not yet sufficient. This (short) [annex to the package vignette](http://polmine.github.io/polmineR/articles/vignette.html#annex-ii-setting-the-corpus_registry-environment-variable) is certainly not yet  enough.

To use the corpora described in a system registry, you need to set the environment variable "CORPUS_REGISTRY" before loading polmineR. Use `Sys.getenv("CORPUS_REGISTRY")` to learn whether it is set. 

```r
Sys.getenv("CORPUS_REGISTRY") # as a check, presumably not available yet
Sys.setenv(CORPUS_REGISTRY = "/PATH/TO/YOUR/REGISTRY") # insert location of your registry!
library(polmineR)
```

Note that polmineR will use a temporary registry that will integrate registry files from your system registry and copies of registry files for corpora that are wrapped in R packages (such as GermaParl). So if you call `registry()` **after** loading polmineR, it is expected behaviour that a temporary directory is returned.

A new version of polmineR available at the GitHub development branch resets the registry to the original state if you unload the package. The option polmineR.corpus_registry (`options("polmineR.corpus_registry")`) captures the system registry for the time polmineR is loaded. But this is available only with the development version (install it via `devtools::install_github("PolMine/polmineR", ref = "dev")`).

**Comment by kairelandkuiper** [comment]
Thank you! 
When I did this and ran both
library(polmineR) and
devtools::install_github("PolMine/polmineR", ref = "dev")

These are the errors that came up: 
R version 3.5.3 (2019-03-11) -- "Great Truth"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Workspace loaded from ~/.RData]

> library(cwbtools)
> library(devtools)
Loading required package: usethis
> Sys.getenv("CORPUS_REGISTRY")
[1] ""
> Sys.setenv("CORPUS_REGISTRY" = "/Users/kirelandkuiper/Desktop/rcqp")
> library(polmineR)
REGISTRY ERROR (/private/var/folders/d8/bfbqpm911ps4wpz_4g18x3yr0000gn/T/RtmpuGIVZZ/polmineR_registry/ukvapes): syntax error
REGISTRY ERROR (/private/var/folders/d8/bfbqpm911ps4wpz_4g18x3yr0000gn/T/RtmpuGIVZZ/polmineR_registry/ukvapes): Error parsing the main Registry structure.
REGISTRY ERROR (/private/var/folders/d8/bfbqpm911ps4wpz_4g18x3yr0000gn/T/RtmpuGIVZZ/polmineR_registry/usvapes): syntax error
REGISTRY ERROR (/private/var/folders/d8/bfbqpm911ps4wpz_4g18x3yr0000gn/T/RtmpuGIVZZ/polmineR_registry/usvapes): Error parsing the main Registry structure.
Error: package or namespace load failed for ‘polmineR’:
 .onLoad failed in loadNamespace() for 'polmineR', details:
  call: path.expand(path)
  error: invalid 'path' argument
> devtools::install_github("PolMine/polmineR", ref = "dev")
Downloading GitHub repo PolMine/polmineR@dev
✔  checking for file ‘/private/var/folders/d8/bfbqpm911ps4wpz_4g18x3yr0000gn/T/RtmpuGIVZZ/remotesaadab735ed9/PolMine-polmineR-024b89b/DESCRIPTION’ (346ms)
─  preparing ‘polmineR’: (500ms)
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts (346ms)
─  checking for empty or unneeded directories
─  building ‘polmineR_0.8.0.9014.tar.gz’
  
REGISTRY ERROR (/private/var/folders/d8/bfbqpm911ps4wpz_4g18x3yr0000gn/T/Rtmpwa7uSA/polmineR_registry/us): syntax error
REGISTRY ERROR (/private/var/folders/d8/bfbqpm911ps4wpz_4g18x3yr0000gn/T/Rtmpwa7uSA/polmineR_registry/uk): Error parsing the main Registry structure.
REGISTRY ERROR (/private/var/folders/d8/bfbqpm911ps4wpz_4g18x3yr0000gn/T/Rtmpwa7uSA/polmineR_registry/): syntax error
REGISTRY ERROR (/private/var/folders/d8/bfbqpm911ps4wpz_4g18x3yr0000gn/T/Rtmpwa7uSA/polmineR_registry/usvapes): Error parsing the main Registry structure.
Error: package or namespace load failed for ‘polmineR’:
 .onLoad failed in loadNamespace() for 'polmineR', details:
  call: path.expand(path)
  error: invalid 'path' argument
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/polmineR’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/polmineR’
Error: Failed to install 'polmineR' from GitHub:
  (converted from warning) installation of package ‘/var/folders/d8/bfbqpm911ps4wpz_4g18x3yr0000gn/T//RtmpuGIVZZ/fileaada6e4b277b/polmineR_0.8.0.9014.tar.gz’ had non-zero exit status

Is it a problem with my CQP registry structure? Thank you for your help!

**Comment by PolMine** [comment]
Dear Katie,

thanks a lot. Your feedback is really a great help to improve the documentation.

The REGSITRY ERROR we see might indicate that there is a some file in the registry directory that violates the standardization for these files. Could you run the following code and report the results?

```
library(polmineR)
library(cwbtools)
packageVersion("polmineR")
registry_dir <- "/Users/kirelandkuiper/Desktop/rcqp"
for (regfile in list.files(registry_dir)){
  message("Checking registry file: ", regfile)
  print(readLines(file.path(registry_dir, regfile)))
  print(cwbtools::registry_file_parse(corpus = regfile))
}
```

The [CWB Encoding Tutorial](http://cwb.sourceforge.net/files/CWB_Encoding_Tutorial.pdf) includes an example (p. 20) what a registry file should look like. Essentially, it defines a directory where the binary corpus data reside, corpus properties, and most importantly, structural and positional attributes. 

In CWB parlance, the "registry" is a directory is a directory with a set of registry files defining the corpora on your system. I would expect that we may see that one of the registry files is a non-standard registry file. Let's see ...

**Comment by kairelandkuiper** [comment]
Here are the results! The directory I am using is the same for the registry files for two CWB-encoded corpora that I created, and they do run on CQP. 

 library(polmineR)
> library(cwbtools)
> packageVersion("polmineR")
[1] ‘0.8.0’
> registry_dir <- "/Users/kirelandkuiper/Desktop/rcqp"
> for (regfile in list.files(registry_dir)){
+   message("Checking registry file: ", regfile)
+   print(readLines(file.path(registry_dir, regfile)))
+   print(cwbtools::registry_file_parse(corpus = regfile))
+ }
Checking registry file: uk
character(0)
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file '/private/var/folders/d8/bfbqpm911ps4wpz_4g18x3yr0000gn/T/Rtmp6Q6Kdj/polmineR_registry/uk': No such file or directory

thank you for the help!

**Comment by PolMine** [comment]
This is not as enlightning as I would have hoped. 

First, can you install the latest development version of polmineR?

```r
install.packages("devtools")
devtools::install_github("PolMine/polmineR", ref = "dev")
```

Actually, handling registry files has not changed. But the mechanism to unload polmineR is cleaner than before.

Second, can you run the previous experiment in a slightly modified fashion. The `cwbtools::registry_file_parse()` function apparantly tries to access the temporary registry directory generated by polmineR, but this was not my intention.

```r
library(polmineR)
library(cwbtools)
packageVersion("polmineR")
registry_dir <- "/Users/kirelandkuiper/Desktop/rcqp"
for (regfile in list.files(registry_dir)){
  message("Checking registry file: ", regfile)
  print(readLines(file.path(registry_dir, regfile)))
  print(cwbtools::registry_file_parse(corpus = regfile, registry_dir = registry_dir))
}
```

Third, would you mind uploading the registry files in your the directory ~/Desktop/rcqp to this issue? As I understand it, there should be two files ("uk", and "us")? But the first output of my short test script (`character(0)`) indicates that the file "uk" might be empty. 

Fourth: I understand you do not have problems to work with your corpora with "traditional" CQP? So this works?

```sh
cqp -r /Users/kirelandkuiper/Desktop/rcqp 
```

Thanks your patience to get this resolved!

**Comment by kairelandkuiper** [comment]
Unfortunately, I was not able to install the updated polmineR package. I ran the following code:

devtools::install_github("PolMine/polmineR", ref = "dev")
Downloading GitHub repo PolMine/polmineR@dev
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                     
2: CRAN packages only      
3: None                    
4: DT (0.12 -> 0.13) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
1
DT (0.12 -> 0.13) [CRAN]
Installing 1 packages: DT
Error: Failed to install 'polmineR' from GitHub:
  (converted from warning) unable to access index for repository https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.5:
  cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.5/PACKAGES


Any suggestions for how to remedy this? Thanks for the help!

**Comment by schtepf** [comment]
A related issue: corpus() doesn't work if Sys.setenv("CORPUS_REGISTRY") is changed after loading the package because internal .list_corpora() always uses registry() while all other functions respect the current setting of CORPUS_REGISTRY.

**Comment by kirelandkuiper** [comment]
This issue is resolved thanks to the documentation! Thanks!!
