### ISSUE TITLE
shiny | code output in kwic with `window` parameter

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#134]
The shiny app now provides the code  which is executed in the background. Here, I noticed something peculiar for the `kwic()` method: A `window` parameter is passed which is neither documented nor actually working in a regular R session. So this would be the code shown by the shiny app:

```
kwic(
  "GERMAPARL",
  query = "Pandemieplan",
  cqp = FALSE,
  positivelist = ,
  window = 10
)
```

In a regular R session the `window` parameter is ignored. The usual parameters to explicitly define the window size would be `left` and `right`. I assume there is a reason why the shiny version of polmineR deviates here, but for the purpose of reproducibility, it might be more useful to return code which actually can be executed in a non-shiny environment, wouldn't it?

NB: I am surprised that the empty `positivelist` parameter which is returned by the shiny app this way doesn't throw an error but this doesn't seem to be an issue.

**Comment by PolMine** [comment]
sYou are perfectly right. The app should be in line with the cdode, so there are two different sliders "left" and "right" now. There is not  discrimination there now.

**Comment by ChristophLeonhardt** [comment]
That seems to do the trick for `kwic()`. The same issue still persists with the `cooccurrence()` method in the app which I did not see before.
