### ISSUE TITLE
count() on partition_bundle rather slow / doesn't scale well?

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#137]
I noticed that performing a count (`count()`) on all tokens of a partition_bundle is rather slow. In addition it doesn't seem to scale too well, although I might need to test this a bit more.

```
library(polmineR)
use("GermaParl")
speeches <- as.speeches("GERMAPARL", s_attribute_name = "speaker") # 162.023 speeches
speeches_count <- polmineR::count(speeches, p_attribute = "lemma")
```

This takes 18 minutes on my machine according to `system.time()`

Performing the same operation on a bundle with more partitions but similar size takes quite a bit longer: 

```
library(polmineR)
use("GermaParl")
speeches <- as.speeches("GERMAPARL", s_attribute_name = "speaker", gap = 50) # 243.669 speeches 
speeches_count <- polmineR::count(speeches, p_attribute = "lemma")
```

~ 43 minutes. 

This can get quite slow the larger the bundle gets.

**Comment by ChristophLeonhardt** [comment]
Just a little update: It seems that **enriching** a partition_bundle is quite a bit faster than performing a **count** on it. Both create a count_bundle object (among others) which can be used, for example, for creating a sparse matrix. 

```
library(polmineR)
use("GermaParl")
pb <- partition_bundle("GERMAPARL", s_attribute = "speaker")
pb_count <- polmineR::count(pb, p_attribute = "lemma") # 63 seconds
pb_enrich <- polmineR::enrich(pb, p_attribute = "lemma") # 22 seconds


dtm_count<- polmineR::as.sparseMatrix(pb_count, col = "count")
dtm_enrich <- polmineR::as.sparseMatrix(pb_enrich, col = "count")
```

Two caveats: 

1) This is not directly available for `as.speeches()` because enriching the `plpr_subcorpus` class is not possible.
2) I am not 100% sure if that actually results in identical Document-Term-Matrices:

```
identical(dtm_count, dtm_enrich) # is false
which(!rownames(dtm_enrich) %in% rownames(dtm_count)) # is 0
which(!colnames(dtm_enrich) %in% colnames(dtm_count)) # is 0
```

So they are not identical but both row and column names are the same. However, value wise there are differences. 

```
all(slam::col_sums(dtm_enrich) == slam::col_sums(dtm_count))
all(slam::row_sums(dtm_enrich) == slam::row_sums(dtm_count))
```

This probably warrants a new issue, I'll open now.

**Comment by PolMine** [comment]
To address the performance issue, I somewhat reworked the `as.DocumentTermMatrix()`-method for the `partition_bundle` class. It should be significantly faster now (50% of time previously required). Your observation whether the method scales well might indicate that your machine runs out of memory. Do you have any further observations on that?

I should also like a third way to generate a `DocumentTermMatrix` that may be a fast alternative.

```r
library(polmineR)
use("GermaParl")
dtm <- as.DocumentTermMatrix("GERMAPARL", s_attribute = "speaker", p_attribute = "word")
```

I will be glad to receive further feedback on performance!

**Comment by ablaette** [comment]
Things have become faster. See this scenario ... 

```r
library(polmineR)
speeches <- as.speeches("GERMAPARL", s_attribute_name = "speaker") # 162.023 speeches
speeches_count <- count(speeches, p_attribute = "lemma", progress = TRUE, verbose = TRUE)
```

Takes 1-2 minutes on my machine.
