### ISSUE TITLE
Use corpora in pkg selectively

### ISSUE THREAD

**Issue by PolMine** [PolMine/polmineR#138]
The `use()`-method will activate all corpora in a package. If a package contains several corpora, it may be useful to make only a subset of the corpora or one single corpus available. This would require to add the argument corpus to the method. Something like this.

```r
use(pkg = "GermaParl", corpus = "GERMAPARL")
```

**Comment by ablaette** [comment]
Has been implemented, available on the dev branch, and in upcoming v0.8.7 CRAN release.
