### ISSUE TITLE
Queries over aligned corpora, is that possible?

### ISSUE THREAD

**Issue by hsang** [PolMine/polmineR#14]
Dear all,

I was wondering if there is any way to execute a query (create a subcorpus) over an aligned corpora using PolMine. I mean, I have two corpora that are aligned according to CWB documentation using _cwb-align-import_ command.  I can executes queries over them using CWB commands, for instance:

> >PARALELL_CORPUS1  # I choose PARALLEL_CORPUS1 to make queries
> >show PARALLEL_CORPUS2 # I select corresponding parallel corpus to show alignments
> >"is" # This query shows results in PARALELL_CORPUS1 and the pertinent aligned sentence in PARALLEL_CORPUS2

So, is there any chance to do something similar using PolMine package?

Thank you for your help and attention.

Best,
Hugo

**Comment by PolMine** [comment]
Dear Hugo,
sorry for not answering earlier. Admittedly, polmineR was not designed with aligned corpora in mind, and I admittedly do not have experience with aligned corpora. Is there a specific scenario you would have in mind and that cannot be handled with the usual CQP syntax? 
Kind regards, Andreas

**Comment by hsang** [comment]
Dear Andreas,

first of all thank you for your help and sorry about my late response. 
Yes, I can handle parallel queries with CQP syntax without any problem. I asked out of mere curiosity, because I needed to make parallel queries and I was considering using only PolMine funcionalities. 

Thanks for your response.

Best regards, Hugo
