### ISSUE TITLE
get_token_stream() | subset only works when length of p_attribute > 1 if input is partition bundle

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#141]
There is something peculiar going on with `get_token_stream()`. Assuming that I just want to remove stop words from a token stream using the subset argument, given the examples provided, I would try: 

```
library(polmineR)
stopword_vector <- tm::stopwords("de")

gpm_ts <- get_token_stream(
  "GERMAPARLMINI",
  p_attribute = "word",
  subset = {!word %in% stopword_vector},
  progress = TRUE
)
```

This works! It also works with a partition. It does not work using a partition bundle object as input. 

```
gpm_parties <- partition_bundle("GERMAPARLMINI", s_attribute = "party")

gpm_parties_ts <- get_token_stream(
  gpm_parties,
  p_attribute = "word",
  subset = {!word %in% stopword_vector},
  progress = TRUE
)
```

>  Error in word %in% stopword_vector : object 'word' not found 

The problem here seems to be that while the corpus and partition methods of get_token_stream() return a data.table, for bundles the return value is a character vector if the length of the p_attribute parameter is just 1. But I could be mistaken in this interpretation however. In any case, this is surprising and the error message isn't very helpful in this regard.

**Comment by ablaette** [comment]
Using the `subset` argument works for a `partition_bundle` object, but it does not if `phrases` are `NULL`.

```r
library(polmineR)
gpm_parties <- partition_bundle("GERMAPARLMINI", s_attribute = "party")

queries <- c('"freiheitliche" "Grundordnung"', '"Bundesrepublik" "Deutschland"' )
phr <- corpus("GERMAPARLMINI") %>% cpos(query = queries) %>% as.phrases(corpus = "GERMAPARLMINI")

gpm_parties_ts <- get_token_stream(
  gpm_parties,
  p_attribute = "word",
  subset = {!word %in% stopword_vector},
  phrases = phr,
  progress = TRUE
)
```

So I tried to make the abort message a bit more telling.

**Comment by ablaette** [comment]
I refactored the method such that the limitations do not persist. Please re-open the issue if necessary.
