### ISSUE TITLE
get_token_stream() | more than one p_attribute even if phrases are NULL?

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#142]
This is related to issue #141: According to the documentation, the p_attribute parameter of `get_token_stream()` should be a 

> A length-one character vector, the p-attribute to decode.

In the same documentation entry, it is shown that two p_attributes can be used: 

```
sp <- corpus("GERMAPARLMINI") %>% as.speeches(s_attribute_name = "speaker", progress = FALSE)
queries <- c('"freiheitliche" "Grundordnung"', '"Bundesrepublik" "Deutschland"' )
phr <- corpus("GERMAPARLMINI") %>% cpos(query = queries) %>% as.phrases(corpus = "GERMAPARLMINI")

kill <- tm::stopwords("de")

ts_phr <- get_token_stream(
  sp,
  p_attribute = c("word", "pos"),
  subset = {!word %in% kill  & !grepl("(\\$.$|ART)", pos)},
  phrases = phr,
  progress = FALSE,
  verbose = FALSE
)
```

Apparently, this only applies if the phrases parameter is not NULL. 

I do not see an inherent rationale why phrases and the length of p_attributes should be connected. I could imagine scenarios in which I want to remove stop words from a token stream without taking into account phrases for example. 

In any case, the documentation is probably not up to date because the p_attribute argument can be a character vector of length one or higher if used with phrases.

**Comment by ablaette** [comment]
It is now possible to use multiple p-attributes, irrespective of the usage of `phrases`.
