### ISSUE TITLE
boundary in KWIC does throw error if length of object equals 1 (because of trim progress bar)

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#149]
# Problem

In `kwic()` it is possible to define a s-Attribute as a boundary the window should not exceed. This works perfectly fine except for instances in which the keyword only occurs once. In this case, the progress bar of the trim-Method doesn't work because min = max. 

# Reproducible Example

The first example has exactly two hits and works fine.
```
library(polmineR)
kwic("GERMAPARLMINI", query = '[word = "Wolfgang"] [word = "Schäuble"] [word = ","]', cqp = TRUE, regex = TRUE, boundary = "date")
```

The following example query has exactly one hit and does not:

```
kwic("GERMAPARLMINI", query = '[word = "Wolfgang"] [word = "Schäuble"] [pos = "V.*"]', cqp = TRUE, regex = TRUE, boundary = "date")
```

> ... checking that context positions to not transgress regions
... checking that all s-attributes are available
... get struc for s-attribute: date
... checking boundaries of regions
 Error in txtProgressBar(min = 1, max = object@count, style = 3) : 
  must have 'max' > 'min' 

Version: polmineR_0.8.1

# Possible fix

I think, the culprit is `ctxt <- trim(ctxt, s_attribute = boundary, verbose = verbose, progress = progress)` (line 400 in kwic.R), which calls trim which contains the line `if (progress) pb <- txtProgressBar(min = 1, max = object@count, style = 3)` (line 79 in trim.R).  

Given the error message, I think its plausible to check if length(object@count) > 1 and otherwise not to call the progress bar but maybe I am missing something or there is a more elegant solution.

**Comment by ablaette** [comment]
The argument `progress` was used/necessary by an older approach for checking the boundary. Refactoring the procedure makes the progress bar obsolete. I removed the argument from `kwic()`.
