### ISSUE TITLE
merge context and cooccurrences-method to get cooccurrences/collocations

### ISSUE THREAD

**Issue by PolMine** [PolMine/polmineR#15]
The current situation is not very logical (naming of context-method to get cooccurrences).

**Comment by ablaette** [comment]
That is solved in v0.7.3 submitted to CRAN. The context method is now a worker that will usually not be used directly. The cooccurrences method returns the co-occurrences for one query. To get all cooccurrences in a corpus, consult the polmineR.graph package that includes a (new) Cooccurrences class.
