### ISSUE TITLE
Feature Request | Pass Word List to CQP-Query

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#150]
In Issue #92 you discussed the possibility to pass multiple queries to a method at once. 

This is very helpful but as far as I see it, it doesn't cover a scenario in which I want to pass a list of terms **to a query** like it is explained on page 35 of the CQP-Language Tutorial (http://cwb.sourceforge.net/files/CQP_Tutorial.pdf), Section 6.2.

The `[lemma = $list]` expression seems pretty elegant and might make life easier when writing more complex queries with multiple variables. 

Essentially, I envision turning the Query "Lemma A or Lemma B followed by POS X or POS Y" written like this:

```
query = '([lemma = "A"]|[lemma = "B"]) ([pos = "X"]|[pos = "Y"])'
```

into 

```
lemma_list <- list("A", "B")
pos_list <- list("X", "Y")
query = '[lemma = lemma_list] [pos = pos_list]'
```

I assume that these queries would have the same result. I think - and there might be good reasons that this isn't the way to go - that this might be useful for queries in which the lists contain a number of tokens or if there is a number of lists to put into a query. It is also quite possible that there is solution for this already but I didn't find it. In any case, thank you.

**Comment by ablaette** [comment]
A late response: I think it is close to impossible to let CQP process a list / vector that is defined as an R project. Absolutely no idea how I would make the C code of CQP process my R object. 

The best way to got is regular expressions, something like this.

```r 
query <- '[lemma = "(A|B)"][pos = "(X|Y)"]'
```

And of course you could use some R code to generate the query:

```r
lemma <- c("A", "B")
pos <- c("X", "Y")
query <- sprintf('[lemma = "%s"][pos = "%s"], paste(lemma, collapse = "|"), paste(pos, collapse = "|"))
```

Not quite as elegant as traditional CQP, but it should be efficient, too.
