### ISSUE TITLE
cooccurrences command fails when dt object already exists in the environment

### ISSUE THREAD

**Issue by cgnguyen** [PolMine/polmineR#152]
I have a small error using the cooccurrences that I traced back to having an object called dt already in the environment. 

This works just fine:
`cooccurrences("GERMAPARL",` query = 'Migrationshintergrund', left = 10, right = 10)` 

But this does not. 
`dt<-NULL`
`cooccurrences("GERMAPARL", query = 'Migrationshintergrund', left = 10, right = 10)`
Not a major problem, but wanted to highlight it. Thank you for the program!

**Comment by ablaette** [comment]
Important observation and certainly hard to turn this into a reproducible example. I admit, I cannot reproduce the error. I had hoped that some rework of `cooccurrences()` in the meantime has solved the issue. But even with polmineR v0.8.0 I do not get the error. Maybe R has changed ... Please let me know if you still see the issue.
