### ISSUE TITLE
'Pandoc and/or pandoc-citeproc not available' error at CRAN 

### ISSUE THREAD

**Issue by PolMine** [PolMine/polmineR#154]
The CRAN test results show the following error for macOS and Solaris:

------------------------------------------

checking re-building of vignette outputs ... [7s/7s] WARNING
Error(s) in re-building vignettes:
  ...
--- re-building ‘OpenCPU.Rmd’ using rmarkdown
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
--- finished re-building ‘OpenCPU.Rmd’

--- re-building ‘vignette.Rmd’ using rmarkdown
Warning in engine$weave(file, quiet = quiet, encoding = enc) :
  Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
... activating corpus: GERMAPARLMINI (version: 0.0.1 | build date: 2019-02-23)
... activating corpus: REUTERS
Quitting from lines 123-124 (vignette.Rmd)
Error: processing vignette 'vignette.Rmd' failed with diagnostics:
cannot open the connection
--- failed re-building ‘vignette.Rmd’

--------------------------------------------

It is possible to build the vignette if the evaluation of code chunks causing errors depends on the result of `rmarkdown::pandoc_available()`. But actually, I think the `knit_print()`-method should do the check?

**Comment by ablaette** [comment]
The `knit_print()`-method checks using `rmarkdown::pandoc_available()` and this CRAN issue is not there any more.
