### ISSUE TITLE
Rounding errors

### ISSUE THREAD

**Issue by PolMine** [PolMine/polmineR#155]
The following, somewhat adapted chunk from the package vignette will not yield the table with rounded numeric columns as one would expect.

```r
library(polmineR)
saudi_arabia <- partition("REUTERS", places = "saudi-arabia", regex = TRUE)
saudi_arabia <- enrich(saudi_arabia, p_attribute = "word")

saudi_arabia_features <- features(saudi_arabia, "REUTERS", included = TRUE)
saudi_arabia_features_min <- subset(saudi_arabia_features, rank_chisquare <= 10.83 & count_coi >= 5)
saudi_arabia_features_min

format(saudi_arabia_features_min, 2)
```
Even worse, after having run this chunk, you witnesss some very strange rounding behaviour.

```r
round(1.123344566, 2)
```

**Comment by ablaette** [comment]
This is an old issue - and I do not think the issue persists. The `chisquare()` method internally resets the number of digits (`options(digits = 20)`) and restores the original value on exit. This has not always been like this. Even without reconstructing when this has changed, I feel safe to close the issue.
