### ISSUE TITLE
Efficient workflow to decode sentences of corpus

### ISSUE THREAD

**Issue by ablaette** [PolMine/polmineR#176]
Getting a list of sentences would be possible by something like `corpus() %>% split() %>% get_token_stream()`. This may not be very efficient. A nice and efficient workflow might work as follows:

```r
corpus("REUTERS") %>%
  regions(s_attribute = "s") %>%
  get_token_stream(split = TRUE)
```

Or, alternatively:

```r
corpus("REUTERS") %>%
  segment(s_attribute = "s") %>%
  get_token_stream(split = TRUE)
```

**Comment by ablaette** [comment]
A new polmineR version on the dev branch (v0.8.5.9011) now includes an implementation of the first option that occurred to me. Generally speaking, the implementation is much faster than the original approach and performance is satisfactory. The bottleneck is a `cut()` call. No idea so far how I could speed this up. But as I said, the performance boost is significant already.

**Comment by ChristophLeonhardt** [comment]
This is a fine solution. However it does not yet work with subcorpora. It splits the entire corpus even if you do insert a `subset()` in the pipe before `regions()`.

**Comment by ablaette** [comment]
Good point. I now implemented a `regions()` method for `subcorpus` objects. This is an example I played with.

```r
x <- corpus("GERMAPARL_PARLACLARIN_III") %>% 
  subset(year = "2017") %>%
  regions(s_attribute = "s") %>%
  get_token_stream(split = TRUE)
```

Performance is ok, I think.
