### ISSUE TITLE
context() method for partition_bundle always requires positivelist

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#178]
The way the `context()` method is implemented for partition_bundle objects always requires a positivelist. If you do not provide it, an error occurs: 

> Error in .local(.Object, ...) : object 'positivelist' not found 

I think that at least this is a rather confusing error message and it might sometimes be useful to use `context()` with a partition bundle while not using a positivelist.

**Comment by ablaette** [comment]
Perfectly true. Using the positivelist argument is now optional. On this occasion, I also introduced an (optional) stoplist argument.
