### ISSUE TITLE
Misleading error message when using subset with non-existing s-attribute on subcorpus

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#179]
### Problem
A misleading error message is shown when you perform a subset with a non-existing s-attribute on a subcorpus. This isn't that much of an issue in most applications (because troubleshooting and finding the misspelled s-attribute is often rather easy) but in some situations a typo in a s_attribute name might cause some headache if it isn't clearly stated that the s-attribute simply doesn't exist.

### Example Code

So while this works as expected: 

```
library(polmineR)
sc1 <- subset("GERMAPARLMINI", speaker == "Norbert Lammert") %>%
  subset(party == "CDU_CSU") 
```

This

```
sc2 <- subset("GERMAPARLMINI", speaker == "Norbert Lammert") %>%
  subset(obviously_non_existing_s_attribute == "CDU_CSU") 
```

provokes the following error message:

>  Error in .s_attributes_stop_if_nested(corpus = x@corpus, s_attr = s_attr) : 
  Differing attribute size of s-attributes detected (), but the method does not (yet) work for nested XML / nested structural attributes. 

The problem described in the message is obviously not the problem of the code. It would be useful if it would say that the s-attribute isn't available. This is actually the behavior of the `partition()` method:

```
sc3 <- partition("GERMAPARLMINI", speaker = "Norbert Lammert") %>%
  partition(obviously_non_existing_s_attribute = "CDU_CSU") 
```

>  Error in .local(.Object, ...) : 
  some or all s-attributes provided are not available: obviously_non_existing_s_attribute

### Side Note
On a side note, maybe notice the difference between these two lines: 

```
sc4 <- subset("GERMAPARLMINI", obviously_non_existing_s_attribute == "Norbert Lammert")
```
> Error in file(con, "rb") : cannot open the connection

```
sc5 <- partition("GERMAPARLMINI", obviously_non_existing_s_attribute = "Norbert Lammert")
```
>   Error in .local(.Object, ...) : not all s-attributes are available 

The `partition()` method is more telling here.

**Comment by ablaette** [comment]
`subset()` now returns NULL and issues a telling warning if subcorpus creation fails.
