### ISSUE TITLE
Error in count_method.R, object 'mc' not found

### ISSUE THREAD

**Issue by mxi-hug** [PolMine/polmineR#18]
### Fehlermeldung
```
> Merkel$count() 
Fehler in blapply(as.list(c(1:nrow(.self$partition@cpos))), f = .makeWindows,  :   Objekt 'mc' nicht gefunden
```
### Eingrenzung und Workaround
in count_method.R ist `mc = getOption("polmineR.cores") `
`getOption("polmineR.cores")` antwortet mit `2`, laut manpage sollte `mc = logical, whether to use multicore (defaults to FALSE)`.

Schneller workaround, der keine Lösung ist:
`mc <- FALSE`

**Comment by ablaette** [comment]
Thanks a lot for the feedback. I am currently preparing a new polmineR version (0.7.3) that includes a major rework (i.e. performance improvements) of the count method. The best performance is achieved when polmineR.Rcpp is installed.
So I suggest to install the most recent version of polmineR from the dev branch:
```r
devtools::install_github("PolMine/polmineR", ref = "dev")
```
I will be happy to learn whether the error keeps occurring.

On this occassion, some background information on planned work on the blapply method. An important concern is to offer progress bars during multithreaded operations. I realized that the mclapply function from the mcapply package does this much more stable than my solution. So in the next polmineR version (0.7.4) I will replace my murky solution with the much more stable one from the mcapply package.

**Comment by mxi-hug** [comment]
Thanks for the hint. I updated the polmineR, although the fix was installing polmineR.Rcpp. Apparently, I got the problem completely wrong. The error was not due to count_method.R but in the function "count" from the Cooccurrences class in polmineR.graph. Wrong method, wrong package, wrong repository. My mistake. 

Maybe you could make it clearer that the polmineR.graph depends heavily on the polmineR.Rcpp.

**Comment by ablaette** [comment]
Good point. Thanks a lot for your feedback! So I will close the issue ...
