### ISSUE TITLE
First column in KWIC analysis missing

### ISSUE THREAD

**Issue by svenjakopyciok** [PolMine/polmineR#184]
When I run KWIC analyses, the output does not show the first column anymore, the one indicating which row it is. It is just a minor issue but the column is very convenient for the read-command in a subsequent in-text analysis.
To provide an example: 

kwic("MIGPARL", query = "Kopftuch", s_attributes = c("party", "date"), verbose = FALSE)

K <- kwic("MIGPARL", query = "Kopftuch", s_attributes = c("party", "date"), verbose = FALSE)
read(K, i = 1)

Thanks for all your hard work and help.

**Comment by ablaette** [comment]
Row numbers are back!
