### ISSUE TITLE
README installation for macOS outdated

### ISSUE THREAD

**Issue by ablaette** [PolMine/polmineR#190]
The current README says that macOS binaries are not available. But they are ... So it is only the following steps that are necessary to get started with polmineR on macOS:

- Install R (from CRAN)
- Install RStudio
- Install Command Line Developer Tools
- install polmineR

```r 
install.packages("polmineR")
```

The README should be updated accordingly. And it would be nice to learn something about installation on macOS / M1.

**Comment by ablaette** [comment]
@Christoph - will be glad for your feedback on the new README version!

**Comment by ChristophLeonhardt** [comment]
It looks great. I have some very small suggestions here. I start with the macOS specific typos, etc. At the end of this post, I will add some other typos as well, although the issue isn't concerned with that. I hope that's okay.

### Installation of XQuartz and Command Line Tools is referenced twice without addressing this:

This part of the README suggests installing the aforementioned tools:

https://github.com/PolMine/polmineR/blob/09212f844b14b7f11e57b89495828d3f45607008/README.md?plain=1#L321-L325

The installation of these has already been suggested a few lines earlier. Maybe starting the paragraph or the second sentence with "If you haven't done so already, XQuartz and the Command Line Developer Tools must be installed...", or something like this. Just to address that this has been suggested before.

### Typo and motivation

The following line addresses installing `RcppCWB`. 

https://github.com/PolMine/polmineR/blob/09212f844b14b7f11e57b89495828d3f45607008/README.md?plain=1#L346

I have two comments here:
* there is a typo here. I assume that it should read "If you want or **have** to install..."
* this is connected with my second remark: It remains a bit unclear what RcppCWB is and when or why I would want or have to install its development version. Maybe this can be addressed briefly by adding a sentence like "polmineR interacts with the Corpus Workbench via RcppCWB, an R package which exposes the functions of the CWB." Then it is a bit more clear that this might have to do with the development of polmineR as well.

As I said before, I have very little remarks on the description of the installation here. 

### Other remarks

* this line refers to an old URL: 

https://github.com/PolMine/polmineR/blob/09212f844b14b7f11e57b89495828d3f45607008/README.md?plain=1#L48

* there are still references to `use()` in the tutorial:
https://github.com/PolMine/polmineR/blob/09212f844b14b7f11e57b89495828d3f45607008/README.md?plain=1#L222
https://github.com/PolMine/polmineR/blob/09212f844b14b7f11e57b89495828d3f45607008/README.md?plain=1#L235
https://github.com/PolMine/polmineR/blob/09212f844b14b7f11e57b89495828d3f45607008/README.md?plain=1#L419

* here is a missing whitespace in one line: 

https://github.com/PolMine/polmineR/blob/09212f844b14b7f11e57b89495828d3f45607008/README.md?plain=1#L250

**Comment by ablaette** [comment]
thanks a lot for the feedback, just pushed a new version
