### ISSUE TITLE
shiny graphical web interface dies when user clicks on kwic result row

### ISSUE THREAD

**Issue by jthale76** [PolMine/polmineR#192]
Here at the University of Georgia we are running polmineR 0.8.5 with Shiny Server Pro v1.5.15.1067
The experimental shiny web app mostly works but after running a KWIC search, if you click on an individual word-in-context, the whole thing dies a horrible death

Listening on http://127.0.0.1:45841
Warning in shiny::incProgress(amount = 1, detail = msg) :
  incProgress was called outside of withProgress; ignoring
Warning in shiny::incProgress(amount = 1, detail = msg) :
  incProgress was called outside of withProgress; ignoring
Warning in shiny::incProgress(amount = 1, detail = msg) :
  incProgress was called outside of withProgress; ignoring
Warning: Error in <Anonymous>: assignment of an object of class “NULL” is not valid for @‘s_attribute_strucs’ in an object of class “partition”; is(value, "character") is not TRUE
  80: stop
  79: <Anonymous>
  78: .local
  77: partition
  75: .local
  74: polmineR::html
  72: observeEventHandler
   1: runApp
Execution halted

**Comment by ablaette** [comment]
My apologies for a terrible delay to respond. I hope I addressed this issue in a new development version (dev branch). The problem we had was that if you click on a row of the KWIC display, the machine would not know which structural attribute would define the region / corpus subset to display.

If the corpus has a template with a default s-attribute to expand to, this issue does not arise. If not: There is now a modal dialogue explaining this, and no crash. And if you include s-attributes into the kwic table, it is assumed that you want to use the displayed s-attributes as a basis for fulltext output. 

Thanks a lot for raising the issue. I will be glad if everything works now as intended.

**Comment by jthale76** [comment]
thank you so much Andreas... where can we go to learn about "templates"? It's likely that as we add corpora we are going to need to adjust things like Default s-attribute. If there is no existing documentation, please consider this a Feature Wish :)
