### ISSUE TITLE
as.speeches doesn't work for nested corpora

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#198]
With **coi** being a nested corpus, this does not work:
```
lp_speeches <- as.speeches(coi,  
            s_attribute_name = "speaker", 
            s_attribute_date = "date")
```

This results in:

> Fehler in .local(.Object, ...) : 
Number of regions for s_attribute 'date' and s_attribute 'speaker' not identical - procedure will not work

Edit: Another error message appears if the object is a subcorpus created by subset based on a nested corpus: 

```
lp <- subset(coi, lp == 17)

lp_speeches <- as.speeches(lp, 
            s_attribute_name = "speaker", 
            s_attribute_date = "date")
```

> Fehler in .Object[i, 1] : Indizierung außerhalb der Grenzen

**Comment by ablaette** [comment]
Just pushed on the dev branch a new polmineR version that makes `as.speeches()` work for `corpus` objects if the corpus is nested. Uses new RcppCWB functions `s_attr_is_sibling()` and `s_attr_is_descendent()`. Let me know if it works, and please note that I have not yet taken care of the method for `partition` objects.

**Comment by ablaette** [comment]
And I now pushed an update that implements digesting nested XML when applying `as.speeches()` on a `partition` object. It is hard to make this fast - but I will take care of performance another time.
