### ISSUE TITLE
knit_print for textstat object (features) doesn't work for ngrams

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#200]
If you want to print textstat objects using knit_print, the method assumes a positional attribute as a column name. As the example below (which has been adapted from [the slide here](https://polmine.github.io/UCSSR/features.html#17)) shows, this doesn't have to be the case.

```
cdu_csu_ngrams <- partition("GERMAPARLMINI", party = "CDU_CSU", interjection = "speech") %>%
  polmineR::ngrams(n = 2, p_attribute = "word")

bt_ngrams <- partition("GERMAPARLMINI", interjection = "speech") %>%
  polmineR::ngrams(n = 2, p_attribute = "word")

cdu_csu_significant_ngrams <- polmineR::features(cdu_csu_ngrams, bt_ngrams, included = TRUE) %>%
  subset(count_coi >= 5) %>% 
  subset(chisquare >= 10.83)

polmineR::knit_print(cdu_csu_significant_ngrams)
```

The actual error seems to occur when `format()` is applied for features. This requires a column from the p_attribute slot of the features object and is called from `as(x, "htmlwidget")`.

This happens in polmineR version 0.8.5.9019

**Comment by ablaette** [comment]
Thanks for reporting this bug/issue. It is absolutely true that `format()` did not work on `features_ngrams` objects. I used a somewhat abbreviated example to locate the issue. 

```r
library(polmineR)

cdu_csu_ngrams <- partition("GERMAPARLMINI", party = "CDU_CSU", interjection = "speech") %>%
  polmineR::ngrams(n = 2, p_attribute = "word")

bt_ngrams <- partition("GERMAPARLMINI", interjection = "speech") %>%
  polmineR::ngrams(n = 2, p_attribute = "word")

cdu_csu_significant_ngrams <- features(cdu_csu_ngrams, bt_ngrams, included = TRUE)

format(cdu_csu_significant_ngrams)
```

A new version on the dev branch fixes the issue. I also cover the `format()` methods with a unit test now. So I close the issue ...
