### ISSUE TITLE
RStudio crashes on corpus() command - macOS

### ISSUE THREAD

**Issue by abrailey-jones** [PolMine/polmineR#204]
Hello! In our lab at the University of Georgia, we've discovered that RStudio now crashes on macOS with the same registry that worked for putty knife. Once the R environment is configured and polmineR has been loaded, the corpus() command causes RStudio to give a generic abort error message which resets the session. We've tested the same registry and indices on a few iMacs/MacBooks finding that it works with polmineR version 0.8.5 but not with 0.8.6. 

The version details of my personal MacBook:
R version: 4.1.3
RStudio version: RStudio 2022.02.1+461 "Prairie Trillium" Release (8aaa5d470dd82d615130dbf663ace5c7992d48e3, 2022-03-17) for macOS

Thanks!

**Comment by ablaette** [comment]
Thank you so much for reporting this issue. I regret that you face it, but I am confident that I can address it quickly. 

Starting with polmineR v0.8.6, the `corpus()` call uses new functionality of the RcppCWB package that extracts information on corpora from the in-memory representation of corpora that is there once a corpus has been loaded, which includes parsing the registry file. Using this in-memory information is a lot more efficient than parsing the registry file again and again - which has been the approach of polmineR's registry-related utility functionality to date.

Using the in-memory information is not yet fully robust, if a non-standard registry file was the original input. We have seen this during our internal tests when preparing the polmineR v0.8. release - see this issue: PolMine/RcppCWB#62

So please help me to understand the peculiarities of a registry file that leads to the crash (which should not happen). It would be great if you could run the following commands and report what you see (which line causes a crash). 

Essentially what we do is to do step-by-step what `corpus()` does internally.

```r
library(polmineR) # v0.8.6

corpora <- RcppCWB::cqp_list_corpora()
regdirs <- sapply(corpora, RcppCWB::corpus_registry_dir)
charset <- mapply(RcppCWB::corpus_property, corpus = corpora, registry = regdirs, property = "charset")
corpus_type <- mapply(RcppCWB::corpus_property, corpus = corpora, registry = regdirs, property = "type")
data_dirs <- mapply(RcppCWB::corpus_data_dir, corpus = corpora, registry = regdirs)
template <- sapply(data_dirs, function(dir) file.exists(file.path(dir, "template.json")))
 ```

Note that RcppCWB v0.5.2 is required.

One we know which of these commands crashes, we will try to detect, which corpus is the culprit, something like this:

```r
for (x in corpora){print(x); corpus_property(corpus = x, registry = corpus_registry_dir(x), property = "charset")
```

Looking forward to your feedback.

**Comment by abrailey-jones** [comment]
Thank you for the detailed instructions. I apologize for the delay in replying to your response. I've finally had a moment to implement your advice. In preparation to debug, I decided to reinstall both polmineR and RcppCWB since you mentioned it. Interestingly, it seems updating RcppCWB to v0.5.3 has resolved the issue - at least on my personal machine. I'll have to check the version on the lab computers to confirm which version they are on in the coming week. It is possible they are also running an out of date version. I'll close the issue with this info for the time being. Thank you!
