### ISSUE TITLE
partitions without registry_dir paths

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#207]
I attempted to run the following chunk from the slides [here](https://polmine.github.io/UCSSR/sentiments.html#8) with `polmineR 0.8.6.9003`: 

```
df <- context("GERMAPARL", query = "Islam", p_attribute = c("word", "pos"), verbose = FALSE) %>%
  partition_bundle(node = FALSE) %>%
  set_names(s_attributes(., s_attribute = "date")) %>%
  weigh(with = SentiWS) %>% 
  summary()
```

This throws an error in the third line of the pipe in which `s_attributes()` is used. 

This seems to be due to the fact that the slot `registry_dir` in the partition objects in the partition_bundle here is empty which causes the following error message when within `s_attributes()` the `cl_cpos2struc()` function is run.

> Error in check_registry(registry) : 
registry needs to be a length-one character vector

Possibly, one solution is to add the correct fs_path to the partitions' registry_dir slot when creating the bundle. This uses the partition_bundle method for context objects. But I am not quite sure if this addresses the root cause of this change.

**Comment by ablaette** [comment]
The current version on the dev branch fixes the issue with the `registry_dir`. There is a second issue that `context()` currently fails to process multiple p-attributes also addressed by #208.

I used the following code as a check, and as that works, I close the issue.

```r
library(polmineR)

gist_url <- "https://gist.githubusercontent.com/PolMine/70eeb095328070c18bd00ee087272adf/raw/c2eee2f48b11e6d893c19089b444f25b452d2adb/sentiws.R"
devtools::source_url(gist_url) # danach ist Funktion verfügbar
SentiWS <- get_sentiws()

df <- context("GERMAPARL", query = "Islam", p_attribute = "word", verbose = FALSE) %>%
  partition_bundle(node = FALSE) %>%
  magrittr::set_names(s_attributes(., s_attribute = "date")) %>%
  weigh(with = SentiWS) %>% 
  summary()
```
