### ISSUE TITLE
cooccurrences with more than one positional attribute

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#208]
In earlier versions of polmineR, it was possible to pass more than one p-attribute to `cooccurrences()` as illustrated in the slides [here](https://polmine.github.io/UCSSR/cooccurrences.html#16) (the result is shown on the following slide). 

In `polmineR 0.8.6.9003` this does not work anymore. Using the example from the slide here, passing one p-attribute still works as expected. 

```
mmh_query <- '"Menschen" "mit" "Migrationshintergrund"'
cooccurrences("GERMAPARL", query = mmh_query, p_attribute = "word")
```

But adding a second p-attribute as shown in the example throws an error.

```
cooccurrences("GERMAPARL", query = mmh_query, p_attribute = c("word", "pos"))
```

> Error in .region_matrix_context(corpus = corpus, registry = registry, : 
Expecting a single string value: [type=character; extent=2].

**Comment by ablaette** [comment]
Good point. This is the example I use for recovering the ability of `cooccurrences()` to handle two p-attributes:

```r
corpus("GERMAPARLMINI") %>%
  cooccurrences(query = "Arbeit", p_attribute = c("word", "pos"))
```

**Comment by ablaette** [comment]
Fixed.
