### ISSUE TITLE
terms() for subcorpora

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#209]
[These slides](https://polmine.github.io/UCSSR/cooccurrences.html#22) show a method to extract terms from a partition to then identify noisy terms. 

This does not seem to work yet for subcorpora objects created with `subset` (using polmineR 0.8.6.9003).

```
m2008 <- subset("GERMAPARL", year == 2008 & speaker == "Angela Merkel" & interjection == FALSE)
terms(m2008, p_attribute = "word")
```

results in

> Fehler in identical(p_attribute, x@p_attribute) : 
kein Slot des Namens "p_attribute" für dieses Objekt der Klasse "plpr_subcorpus"

The error message is telling. `terms()` (for slice objects) checks early if the p-attribute passed in the function call is identical with a p-attribute in the p_attribute-slot of the subcorpus. But subcorpus has no p_attribute slot.

This still could be user error and I would be glad to learn how I could "enrich" these subcorpora with p_attributes if this would be the way to go.

**Comment by ablaette** [comment]
The method had been implemented for the `slice` virtual class, but the implementation actually only works for `partition` objects. So the method for `subcorpus` objects now relies on the method defined for `partition`.
