### ISSUE TITLE
bug in noise for character vectors in minNchar

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#211]
With `noise()` you are collecting terms in the data which might be considered as noisy in certain regards. If I am not mistaken, in one scenario - minNchar - this is handled the wrong way around. There, the tokens for which the minNchar threshold does not apply (i.e. which are shorter than minNchar) are removed and tokens which are longer than or equal to minNchar are added to the return value of noise. 

If I am right, this line

https://github.com/PolMine/polmineR/blob/7f075e5ad327f1f25fe40afcc29f2caf36113ee8/R/noise.R#L102

should read

```
.Object[terms_to_remove] 
```

instead.

**Comment by ablaette** [comment]
Perfectly true. Fixed.
