### ISSUE TITLE
Documentation of subset()

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#212]
I am not sure if the documentaton of `subset()` is up to date with the current state in polmineR 0.8.6.9003. 

If I run the examples, everything seems to work fine until 

```
sc <- subset(a, speaker = c("Merkel", "Kauder"), regex = TRUE)
```

After this, I would expect that `s_attributes(sc, "speaker")` returns two speaker names. It only returns one. Is this still a valid approach? 

Then, concerning the provision of values as variables in a loop, the documentation suggests using bquote. But is this really necessary? The example in the documentation seems to work as well if you use `sc <- subset(a, speaker == who)` instead. I am just wondering if this is a new development or if the version without `bquote` won't work reliably and thus should be avoided even if it works here?

**Comment by ablaette** [comment]
These are two different issues. The first one is clearly a bug that I just removed ...

**Comment by ablaette** [comment]
The real issue is the bquote one. Maybe `bquote()` is really not required in the for loop, but it should be if we move to `lapply()`, see the following example - which does not work as intended.

```r
library(polmineR)
use("polmineR")

lapply(
  c("Angela Dorothea Merkel", "Volker Kauder", "Ronald Pofalla"),
  function(who){
    print(environment()$who)
    subset(a, bquote(speaker == .(who), where = environment()))
  }
)
```

**Comment by ablaette** [comment]
After some refactoring and adopting quosures from the rlang package, it is now possible to program against `subset()` the envisioned way. See the examples of `subset()`.
