### ISSUE TITLE
Using tooltips() on kwic object removes metadata columns

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#218]
Using the slide [here](https://polmine.github.io/UCSSR/sentiments.html#12) as an example, adding tooltips to a kwic object works fine. However, it does remove the metadata which previously was part of the kwic output. 

So the example of the slide works as intended (the setup of the sentiment dictionary, etc. can be found in the slides, especially [here](https://polmine.github.io/UCSSR/sentiments.html#5). I just changed the example to GermaParlMini).

```
kwic("GERMAPARLMINI", query = "Krise", positivelist = c(words_positive, words_negative)) %>%
  highlight(lightgreen = words_positive, orange = words_negative) %>%
  tooltips(setNames(SentiWS[["word"]], SentiWS[["weight"]]))
```

Adding structural attributes as metadata does not, however. They aren't shown in the output.

```
kwic("GERMAPARLMINI", 
  query = "Krise",
  positivelist = c(words_positive, words_negative), 
  s_attributes = c("date", "party", "speaker")) %>%
  highlight(lightgreen = words_positive, orange = words_negative) %>%
  tooltips(setNames(SentiWS[["word"]], SentiWS[["weight"]]))
```

There is metadata information in the kwic object. And its still there when words get highlighted.

```
kwic("GERMAPARLMINI", 
  query = "Krise",
  positivelist = c(words_positive, words_negative), 
  s_attributes = c("date", "party", "speaker")) %>%
  highlight(lightgreen = words_positive, orange = words_negative) 
```

I believe that `tooltips()` removes the metadata when it performs this `enrich()` line here:

https://github.com/PolMine/polmineR/blob/020771cf19b194d44d84b78726acdf40510731dd/R/tooltips.R#L123

Since `enrich()` has a s_attributes argument also for kwic objects, I think that it would suffice to add `s_attributes = .Object@metadata` to this line to keep the metadata in place.

I did not check if that solution works in all scenarios, for example if the kwic object does not have metadata.

**Comment by ablaette** [comment]
The bug is evident. Thanks for pointing to the correct solution. The unit test I introduced uses this minimal example:

```r
library(polmineR)
use("RcppCWB")

oil <- kwic("REUTERS", query = "oil", s_attributes = "id") %>%
      highlight(list(yellow = "prices")) %>%
      tooltips(tooltips = list(yellow = "alert"))
```
