### ISSUE TITLE
Knitting R Markdown with Tooltips if output is html_document

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#230]
I noticed that using `tooltips` might lead to tokens becoming invisible in the html output of R Markdown documents. I think I found both the reason and a workaround for this, but I am not convinced that this already is the best solution.

I tested this with the following chunk being the only contents of a R Markdown document. The example code is based on the tooltips documentation of polmineR. The output parameter in the yaml header of the R Markdown is `output: html_document`. 

```{r}
library(polmineR)
use(pkg = "RcppCWB", corpus = "REUTERS")

P <- partition("REUTERS", places = "argentina")
H <- html(P)
Y <- highlight(H, lightgreen = "higher")
Tooltip <- tooltips(Y, list(lightgreen = "Further information"))
Tooltip
```

After knitting the document to html, the token "higher" is not visible in the resulting document. This also happens when tooltips should be displayed in keyword-in-context outputs, etc.

Following some investigation, I found out that apparently, the html_document output has a style for spans of class "tooltip" which sets the opacity of the span to 0. This seems to be the problem. See also the same observation here: https://stackoverflow.com/questions/39356288/render-raw-html-in-r-markdown

One workaround is to set the opacity of the class back to 1 manually by inserting the following chunk at the beginning of the R Markdown document.

````
```{css, echo = FALSE}
.tooltip {
  opacity: 1;
}
```
````

Here, this would interfere with every instance of this tooltip class, also from the default R Markdown class, so this probably will have unintendent consequences.

**Comment by ablaette** [comment]
To pick up this issue, I started with a vignette that slightly rewrites the code. "higher" disappears, as described, so I am able to reproduce the issue.

```r
---
title: "tmp"
output: html_document
date: "2023-03-28"
---

```{r}
library(polmineR)
use(pkg = "RcppCWB", corpus = "REUTERS")
library(magrittr)

partition("REUTERS", places = "argentina") %>%
  html() %>%
  highlight(lightgreen = "higher") %>%
  tooltips(list(lightgreen = "Further information"))
```

```

**Comment by ablaette** [comment]
So thanks a lot for the precise analysis of the issue. bootstrap is stronger than polmineR and potentially everywhere. So I opt for the easiest solution, i.e. to rename the CSS classes tooltip and tooltiptext to "tooltipping" and "tooltippingtext". Seems to work - please re-open the issue, if it doesn't.
