### ISSUE TITLE
Adapt to changes in markdown >= v1.3

### ISSUE THREAD

**Issue by yihui** [PolMine/polmineR#235]
Hi @ablaette, I've submitted two PRs and I'm not sure if you have noticed them:

- #232
- #233

I'd truly appreciate it if you could merge them and make a CRAN release at some point. That will give me a little more freedom in making changes in the **markdown** package in the future. Thanks!

**Comment by ablaette** [comment]
Fixed. Many thanks for the PR - and my apologies for taking so long to incorporate this solution. I will submit to CRAN soon!

**Comment by yihui** [comment]
Thank you so much! No need to apologize! I understand that you must have been going through some difficulties.

I feel the tests under https://github.com/PolMine/polmineR/tree/master/inst/fulltext may be too strict, e.g., they are sensitive to changes in white spaces or line breaks, which can prevent me from making such trivial changes in the **markdown** package. I don't know how to improve the tests, but one way to give me a little more freedom is to conditionally run the tests, e.g., on Github Actions only and not on CRAN (`skip_on_cran()`). Would that be okay to you?

**Comment by ablaette** [comment]
`skip_on_cran()` is a very reasonable suggestion, I just implemented that. Thanks a lot for your support, understanding and guidance - and for your great work!

**Comment by yihui** [comment]
Perfect! Please feel free to let me know if I break your tests with critical changes in markdown in future, and I'll be happy to help. Thanks again!
