### ISSUE TITLE
hits method for partition_bundle ignores p_attribute argument

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#239]
I noticed some unexpected behaviour in `count()` for partition bundle objects: The argument `p_attribute` seems to be ignored. I think the actual reason for this is that the p_attribute argument is not really passed to the relevant `cpos()` call in the `hits()` method here: 

https://github.com/PolMine/polmineR/blob/a641992d6e8c1db3e5b488454ae282f2e7fb8b28/R/hits.R#L222

In the example below, I would expect **a** to be the same as **b**. But actually **b** is the same as **c**. If I am correct, all counts on partition bundles are currently performed on the default value of p_attribute for `cpos()` which is `getOption("polmineR.p_attribute")`.

```
library(polmineR)

speeches <- partition("GERMAPARL", year = 2016) |>
  as.speeches(s_attribute_name = "speaker")

a <- count(speeches, query = '[lemma = "Metropole"]', cqp = TRUE)
b <- count(speeches, query = "Metropole", p_attribute = "lemma")
c <- count(speeches, query = "Metropole", p_attribute = "word")

```

**Comment by ablaette** [comment]
Fixed in new dev version, upcoming v0.8.8
