### ISSUE TITLE
Generating an AnnotatedPlainTextDocument requires the specific usage of the p-attribute pos

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#246]
This is not necessarily a bug but I think that this chunk in `as.AnnotatedPlainTextDocument` is quite specific in the way it makes assumptions about the use of the positional attribute `pos`. It assumes that if a positional attribute named `pos` is available, it always refers to Part-of-Speech-Tags of the Stuttgart-Tübingen-Tagset. But while not necessarily likely, the p-attribute `pos` could be used for other information such as POS tags of the UD-Tagset.

So maybe there is a way to avoid hard-coding it like that:

https://github.com/PolMine/polmineR/blob/925f5cf0350a7381739ce81f73b8e9c80215b349/R/decode.R#L82-L87

**Comment by ablaette** [comment]
The new solution is more generic, but I am not sure it is sufficiently generic, see:

```r
if (!"pos" %in% p_attributes(from)) stop("p-attribute not available")
  pos <- get_token_stream(
    from@cpos,
    corpus = from@corpus,
    p_attribute = "pos",
    encoding = from@encoding
  )
  ws_after <- c(ifelse(pos %in% c("$.", "$,"), FALSE, TRUE)[-1], FALSE)
  word_with_ws <- paste(word, ifelse(ws_after, " ", ""), sep = "")
```

**Comment by ablaette** [comment]
The solutation is not yet a good one. Taking the example, it works for the GERMAPARLMINI corpus, but not for GERMAPARL2 (which has annotation xpos and upos).

```r
library(polmineR)
library(NLP)
use("polmineR")

p <- corpus("GERMAPARLMINI") %>%
  subset(date == "2009-11-10" & speaker == "Angela Dorothea Merkel")
a <- as(p, "Annotation")


p <- corpus("GERMAPARL2") %>%
  subset(protocol_date == "2009-11-10") %>%
  subset(speaker_name == "Angela Merkel")
a <- as(p, "Annotation")
```

**Comment by ablaette** [comment]
Using this example to check that the sentence annotation is ok. Consider it fixed.

```r
library(polmineR)
library(NLP)
use("polmineR")

p <- corpus("GERMAPARLMINI") %>%
  subset(date == "2009-11-10" & speaker == "Angela Dorothea Merkel")
a <- as(p, "Annotation")
s <- as(p, "String")
sentences <- s[a[a$type == "sentence"]]


p <- corpus("GERMAPARL2") %>%
  subset(protocol_date == "2009-11-10") %>%
  subset(speaker_name == "Angela Merkel")
a <- as(p, "Annotation")
s <- as(p, "String")
sentences <- s[a[a$type == "sentence"]]

```
