### ISSUE TITLE
Coocurrence statistics without punctuation marks and interjections

### ISSUE THREAD

**Issue by Freschler** [PolMine/polmineR#280]
Is it possible to disregard punctuation marks and interjections (e.g. in GERMAPARL2) when calculating coocurrence statistics?
E.g.:
```r 
merkel_only_speech <- corpus("GERMAPARL2") |>
  subset(protocol_date == "2013-09-03") |>
  subset(speaker_name == "Angela Merkel") |>
  subset(p_type == "speech")`
``` 

If I were now to obtain co-occurrences … 
```r 
co <- cooccurrences(merkel_only_speech, 
                    "Deutschland",
                    left= 10, right= 10)
``` 
... punctuation marks and interjections are part of the collocation analysis, automatically disregarding the ‘real words’ of the speech (within the given span) I’m interested in.

**Comment by ablaette** [comment]
My apologies for responding late. You can use `subset()` for filtering cooccurrences as follows. So we start with ... 

```r
library(polmineR)

merkel_only_speech <- corpus("GERMAPARL2") %>%
  subset(protocol_date == "2013-09-03") %>%
  subset(speaker_name == "Angela Merkel") %>%
  subset(p_type == "speech")
```
And we can exclude puncuation by filtering for the vector `punctuation` that is part of the polmineR package.

```r
co <- merkel_only_speech %>%
  cooccurrences(query = "Deutschland", left = 10, right = 10) %>%
  subset(!word %in% punctuation)
```

A more elegant option would be to use the part-of-speech annotation and to keep only certain types of words.

co <- merkel_only_speech %>%
  cooccurrences(query = "Deutschland", p_attribute = c("word", "upos"), left = 10, right = 10) %>%
  subset(upos %in% c("NN", "ADJ", "VERB"))
```

One general remark: The example you provide is very good, because the subcorpus is small and easy to handle. But you cannot get a lot of statistically significant cooccurrences with such a small subcorpus. So a real-world scenario should explore linguistic structures in a bigger corpus subset.

**Comment by Freschler** [comment]
@ablaette 
Thank you for your response! I realize now that my initial explanation might not have been as clear as it could have been, perhaps due to my limited familiarity with R. Thus, let me clarify:

Both solutions you provided indeed successfully **_filter out_** punctuation marks from the DataTable in R. However, my goal extends beyond just filtering punctuation; I want to exclude punctuation marks before any statistical analysis is conducted. This distinction is crucial for ensuring the accuracy of results for actual words, as failing to exclude punctuation skews the results significantly.

To better illustrate my point, let's consider an example with the word “wenden” & a rather unusual window span (L0 R1):

```r
library(polmineR)
merkel_only_speech <- corpus("GERMAPARL2") %>%
  subset(protocol_date == "2013-09-03") %>%
  subset(speaker_name == "Angela Merkel") %>%
  subset(p_type == "speech")

kwic(merkel_only_speech, query="wenden")
```

The kwic-function yields one hit:  
```graphql
politischer Verfolgung hilfesuchend an Deutschland | wenden | , Anfeindungen von Unbelehrbaren in
```
As can be seen from above,  “wenden” appears once in the sub-corpus, followed immediately by a comma. If we proceed to calculate co-occurrences, the resulting DataTable would be empty, **_not include any co-occurring words_** due to the removal of punctuation marks:

```r
co_2 <- merkel_only_speech %>%
  cooccurrences(query = "wenden", left = 0, right = 1) %>%
  subset(!word %in% punctuation)
```

Yet, what I intend(ed) to achieve is to have the DataTable reflect a statistical (collocational) analysis of the word “Anfeindungen”, which is the immediate first successor of “wenden” in the text – **_excluding punctuation_**. 

I hope this clarifies my 'objective' and the specific challenge I'm facing.
