### ISSUE TITLE
`s_attributes()` for speech bundle does not work for attributes on document level in nested corpora

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#283]
Using GermaParl2 and `polmineR v0.8.9.9001` I noticed that for bundles created by `as.speeches()` `s_attributes()` works in some but not in all circumstances.

It does work for attributes which are on "speaker level" such as "speaker_name" or "speaker_role". It does not work for attributes on the "document level" such as "protocol_date" or "protocol_lp". For these attributes, this results in the following error message:

> Error in check_strucs(corpus = corpus, s_attribute = s_attribute, strucs = struc,  : 
  highest value of strucs may not be larger than size of structural attribute

As an reproducible example:

```
library(polmineR)

speeches_germaparl <- corpus("GERMAPARL2") |>
  as.speeches(s_attribute_date = "protocol_date",
              s_attribute_name = "speaker_name",
              gap = 0)

s_attributes(speeches_germaparl, s_attribute = "protocol_date")
```

For other bundles this works fine.

```
date_bundle <- corpus("GERMAPARL2") |>
  split(s_attribute = "protocol_date")

s_attributes(date_bundle, s_attribute = "protocol_lp")
s_attributes(date_bundle, s_attribute = "speaker_name")
```

**Comment by ablaette** [comment]
Use the following (lightweight) example to check the solution I implemented.

```r
library(polmineR)
use("polmineR")

speeches <- corpus("GERMAPARLMINI") |>
  as.speeches(
    s_attribute_date = "protocol_date",
    s_attribute_name = "speaker",
    gap = 300,
    progress = FALSE
  )

# s-attribute is sibling
s_attributes(speeches, s_attribute = "party")

# s-attribute is ancestor
s_attributes(speeches, s_attribute = "protocol_date")

# s-attribute is descendent
speeches_germaparl <- corpus("GERMAPARLMINI") |>
  split(s_attribute = "protocol_date") %>%
  s_attributes("speaker")
```
