### ISSUE TITLE
decode() fails if nested s-attribute does not occur

### ISSUE THREAD

**Issue by ablaette** [PolMine/polmineR#284]
See the following example.

```r
library(polmineR)
use("GermaParl2")

single_speech <- corpus("GERMAPARL2") |>
  subset(protocol_date == "1949-09-07") |>
  subset(speaker_name == "Erich Köhler") |>
  as.speeches(s_attribute_name = "speaker_name", s_attribute_date = "protocol_date", gap = 0) |> 
  _[[2]]

decode(single_speech, p_attribute = "word", s_attributes = c("protocol_date", "ne"), to = "data.table")
```

**Comment by ChristophLeonhardt** [comment]
I noticed this as well.

I think that this check

https://github.com/PolMine/polmineR/blob/a2e46e9c032552ab389ec19ce6077fe977309f32/R/decode.R#L461

does what it is supposed to do by skipping s-attributes, resulting in missing columns when it is time to set the order of columns in the data.table `y`:

https://github.com/PolMine/polmineR/blob/a2e46e9c032552ab389ec19ce6077fe977309f32/R/decode.R#L500

**Comment by ablaette** [comment]
We add the column with NA values of nested s-attribute does not occurr. Thanks for the extremely helpful analysis.
