### ISSUE TITLE
`decode()` to AnnotatedPlainTextDocument does not work if a document contains only one token

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#285]
I wanted to turn paragraphs from GermaParl2 to `AnnotatedPlainTextDocument`s  using `decode()`. Trying this, I found that there is a case in which this does not work: If the paragraph contains only one token. This results in an error.

### Example

I think that the following example should illustrate this:

```
library(polmineR) # v0.8.9.9001

paragraph <- corpus("GERMAPARL2") %>% 
  subset(speaker_name == "Erich Köhler") %>%
  subset(protocol_date == "1949-09-15") %>%
  subset(p_type == "speech") %>%
  split(s_attribute = "p", value = FALSE) %>%
  .[[2]]

paragraph2 <- decode(
  paragraph,
  to = "AnnotatedPlainTextDocument",
  p_attributes = "word",
  stoplist = polmineR::punctuation,
  verbose = FALSE
)
```

### Possible causes

Since this error occurs only if paragraphs - after the removal of stop words - are only one token long, the length seems to be the issue. I think that there are two lines in `decode()` in which the assumption that documents are longer than one token becomes problematic.

First, if there is only one word, the following line does not work as intended: 

https://github.com/PolMine/polmineR/blob/a2e46e9c032552ab389ec19ce6077fe977309f32/R/decode.R#L96

This causes the next line to concatenate the single token multiple times.

In addition, there is this line which also assumes that there is more than one token:

https://github.com/PolMine/polmineR/blob/a2e46e9c032552ab389ec19ce6077fe977309f32/R/decode.R#L101

### Potential ways to address this

I am not sure whether this fully addresses the problem but the first way would be to check whether the `ts` object has more than one row. If it is longer, the current solution should work well. If not, `ws_after` could be set to FALSE as this would be the last token in any case.

The same could be true for the second line quoted above: If `word_with_ws` contains only one token, then the `left_offset` could be set to 1L. If it is longer, the current solution seems to work.

I did not test this comprehensively, so there might be better solutions.

**Comment by ablaette** [comment]
Perfect analysis. Thanks!
