### ISSUE TITLE
toupper for corpora

### ISSUE THREAD

**Issue by PolMine** [PolMine/polmineR#30]
Very often I am confused whether to provide a corpus uppercase or lowercase. Could you have topupper as default?

**Comment by ablaette** [comment]
Having implemented the `corpus` class and the `corpus()`-method in February/March, I have finally returned to the idea to have a more robust check of the availability of a corpus. The new polmineR version (at the dev branch) will check whether the corpus is available, whether all letters are upper case latters (which is the convention of the CWB), and there will be a suggestion which corpus comes closes to the id provided, if the corpus id provided does not work.
