### ISSUE TITLE
question/feature request: partition() with specific speeches/agenda_items

### ISSUE THREAD

**Issue by mxi-hug** [PolMine/polmineR#34]
Is it somehow possible to create a partition specifically from individual speeches or debates? For the speeches I have the sAttributes date, agenda_item and speaker. I couldn't figure out how to pass parameters to partition() in a specific combination that returns only the specific speeches/agenda_items because partition() returns all possible permutations of the parameters.

Example:

`partition("GERMAPARL", date = c("1997-04-24", "1999-10-01"), agenda_item = c("4", "2"), pAttribute ="word")
`

creates a partition with the four agenda_items

1997-04-24_2
1997-04-24_4
1999-10-01_2
1999-10-01_4

there is a way to limit this to

1997-04-24_4
1999-10-01_2

**Comment by PolMine** [comment]
Thanks for raising the issue. Actually, polmineR should do this nicely. However, generate one partition at a time.
<code>
P1 <- partition("GERMAPARL", date = "1997-04-24", agenda_item = 4)
P2 <- partition("GERMAPARL", date = "1999-10-01", agenda_item = 2)
</code>

To check whether the partitions are what you think it should be, use the `read()`-method

You might also want to have a look at the `as.speeches`-method, which will split up a partition into speeches.

Kind regards, Andreas

**Comment by mxi-hug** [comment]
Thank's for the quick reply. 

I guess, my question was a bit unclear. I was wondering about the case when you have a large list of agenda_items, let's say around 300. My goal was to create a subcorpus containing only agenda_items with more or less the same subject. As a "quick" fix, i looped over the data.table containing the metadata, creating one partition at a time, resulting in a nice `partition_bundle`. This works, but is obviously really slow. Therefore, I was wondering whether the `partition()`-method could accept pairs of `sAttributes` directly. I'm not sure whether this would be a case for `partition` or `partition_bundle` in the polmineR logic.

**Comment by PolMine** [comment]
Thanks for your clarification. Indeed, this is a standard scenario, and your point triggered me to simplify the workflow to get a dictionary-based subset of relevant partitions somewhat by introducing a new `partition_bundle`-method for `partition_bundle`-objects. Starting with polmineR version v0.7.8.9004 (available at the dev branch), the following example illustrates how you can proceed.

Please not: Following conventions that have become common, I have started to move to a snake_case notation. Former camelCase functions, methods and arguments can still be used, as I tried to ensure backwards compatibility.
  
```r
library(polmineR)
use("GermaParl")

pb <- partition_bundle("GERMAPARL", s_attribute = "date", progress = TRUE) # ~ 7 secs 
pb2 <- partition_bundle(pb, s_attribute = "agenda_item", prefix = "agenda_item", progress = TRUE) # ~ 25 secs

dict <- c("Migration", "Zuwanderung", "Einwanderung", "Asyl", "Flucht", "Flüchtlinge")
dict_cnt <- count(pb2, query = dict, p_attribute = "word", progress = TRUE) # ~ 3 secs

# at this stage, you might want to have a look at histograms to determine threshold
dict_cnt_sub <- dict_cnt[TOTAL > 10]

pb_mig <- pb2[[ dict_cnt_sub[["partition"]] ]]

# to see whether we like the result
ai_mig_2016_12_16 <- partition_bundle(pb_mig[["2016-12-16_agenda_item_2"]], s_attribute = "speaker")

speech_frank_schwabe <- ai_mig_2016_12_16[["Frank Schwabe"]]
library(magrittr)
html(speech_frank_schwabe) %>% highlight(list(yellow = dict))
```

**Comment by PolMine** [comment]
As we did not follow up on this conversation, I hope the matter is clarified? Hope it is ok that I close the issue.

**Comment by mxi-hug** [comment]
It is. count in pb did the trick. Thank's a lot!
