### ISSUE TITLE
Not able to install github version of polmineR and GermaParl corpus on Windows < 10

### ISSUE THREAD

**Issue by holnburger** [PolMine/polmineR#35]
I'm not able to install the github version of polmineR and the GermaParl corpus on Windows 7 and Windows 8.1 (it works perfectly fine on Mac OS though).

`devtools::install_github("Polmine/polmineR")` exits with 

```
Downloading GitHub repo Polmine/polmineR@master
from URL https://api.github.com/repos/Polmine/polmineR/zipball/master
Installing polmineR
"C:/PROGRA~1/R/R-34~1.4/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Media/AppData/Local/Temp/RtmpeA5noE/devtools2ac2e393c6b/PolMine-polmineR-4f23df7" --library="C:/Program  \
  Files/R/R-3.4.4/library" --install-tests 

* installing *source* package 'polmineR' ...
Warnung: Ausführung von Kommando 'sh ./configure.win' ergab Status 127
ERROR: configuration failed for package 'polmineR'
* removing 'C:/Program Files/R/R-3.4.4/library/polmineR'
* restoring previous 'C:/Program Files/R/R-3.4.4/library/polmineR'
In R CMD INSTALL
Installation failed: Command failed (1)
```
and `install.packages("GermaParl", repos = "http://polmine.sowi.uni-due.de/packages")` exits with

```
installing the source package ‘GermaParl’

trying URL 'http://polmine.sowi.uni-due.de/packages/src/contrib/GermaParl_1.1.0.9002.tar.gz'
Content type 'application/x-gzip' length 963247053 bytes (918.6 MB)
downloaded 918.6 MB

* installing *source* package 'GermaParl' ...
Warnung: Ausführung von Kommando 'sh ./configure.win' ergab Status 127
ERROR: configuration failed for package 'GermaParl'
* removing 'C:/Program Files/R/R-3.4.4/library/GermaParl'
In R CMD INSTALL
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-34~1.4/bin/x64/R" CMD INSTALL -l "C:\Program Files\R\R-3.4.4\library" C:\Users\Media\AppData\Local\Temp\RtmpeA5noE/downloaded_packages/GermaParl_1.1.0.9002.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘GermaParl’ had non-zero exit status
```

Both times `sh ./configure.win` exits with status 127. It's possible to run sh with Windows 10 whereas former versions of Windows aren't able to run sh out of the box (as far as I know). Is it possible that newer versions of polmineR aren't able to install with Windows < 10?

R Version 3.4.4,
Windows 7 and Windows 8.1,
R-Studio Version 1.1.453

**Comment by PolMine** [comment]
Thanks for raising issues, and my apologies that it took me a while to respond.

The error that you see is not a matter of the Windows version, but signals that the shell ('sh') utility to run bash scripts is not present on your Windows system. The issue can be solved (easily) by installing Rtools, which includes the 'sh' utility wich is required to execute the configure.win shell script. 

However, a somewhat changed logic for handling the registry directory in the most recent version of polmineR (v0.7.9) makes it possible to do without configure.win altogether, which will also skip the requirement to have Rtools installed to install polmineR.

To explain: configure.win adjusts adjusts paths pointing to the data directories with binary corpus files within the package during the installation. However, as polmineR started to generate a temporary registry directory with registry files with adjusted paths upon loading the package, it is not necessary to change paths of the registry file included in the package.

It would confirm my hypotheses, if installing polmineR from the dev branch worked for you:

```r
devtools::install_github("PolMine/polmineR", ref = "dev")
```

Please let me know, whether this works!
Andreas

**Comment by PolMine** [comment]
As we managed to install polmineR on many Windows systems in the meantime, I assume it works? Please let us now if it doesn't.
