### ISSUE TITLE
kwic error

### ISSUE THREAD

**Issue by PolMine** [PolMine/polmineR#36]
With GermaParl, I get an error when calling ...
```r
kwic("GERMAPARL", "Die")
```
Fehler in check_id(corpus = corpus, p_attribute = p_attribute, id = id,  : 
  all corpus positions (cpos) need to be >= 0, not TRUE

**Comment by ChristophLeonhardt** [comment]
Isn't this the same error you fixed in polmineR_0.7.10.9008?

**Comment by PolMine** [comment]
This is perfectly true. Addressing issue #48, this is fixed, so I will close the issue.
