### ISSUE TITLE
corpus as tibble

### ISSUE THREAD

**Issue by systats** [PolMine/polmineR#37]
Hi,

is it possible to get the data in a simple tibble/dataframe format? It would be nice to get all the speeches parsed by speaker, full text, role etc. 

Thanks in Advance,
Syro

**Comment by PolMine** [comment]
Dear Syro,

my apologies for not answering earlier. There has been method `decode()` that offers the functionality you think about. I have turned that into a function now, that can be applied to a corpus, or a partition object. The examples include a scenario to get speeches, and to generate a data.table with the decoded corpus.

Turning the data.table into a tibble is a no-brainer. I did not want to introduce a `as.tibble`-function, to keep dependencies low. 

Is that helpful?

Andreas
