### ISSUE TITLE
Feature Request: Using the != Operator with s_attributes

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#40]
Not equal  to doesn't work:

```{r}
x <- partition("GERMAPARL", party != "CDU")
```

Error: 

 >Fehler in names(def) %in% s_attributes(.Object) : 
  Objekt 'party' nicht gefunden

**Comment by PolMine** [comment]
Dear Christoph,

very good idea. Your suggestion requires to enter the world of non-standard evaluation, which is alien to the recent design of polmineR. Building non-standard evaluation into the partition method would come with a huge risk to break old code, so I was very hesitant to pursue this path.

Anyway, there is now a polmineR version on a temporary "subsetting"-branch that has a non-standard-evaluation-style method zoom, for partition objects, and a new corpus object. The solution is somewhat hacky, but it conveys a sense how non-standard evaluation might work in combination with partitions and corpora. See the the documentation `?"partition-method"` and  `?"corpus-method"`

I will be happy to learn whether you like the look and feel of this.

Kind regards
Andreas

**Comment by ablaette** [comment]
I think development has reached a stage when we can close this issue. Picking up you initial example, this works now with the recent polmineR versions on the dev branch.

```r
library(polmineR)
cdu <- subset("GERMAPARLMINI", party != "CDU")
count(cdu, query = "Migration")
```

See the documentation entry "Subsetting corpora and subcorpora" (`?subset`) for details and examples on using non-standard evaluation.

Thanks again for your great and important feature request!
