### ISSUE TITLE
New knit_print-methods may conflict with pkgdown::build_site

### ISSUE THREAD

**Issue by ablaette** [PolMine/polmineR#41]
The new knit_print-methods are great for including htmlwidgets into Rmarkdown documents. But they generate problems with the ordinary examples for R functions. So the current documentation omits output by catching return values in a variable, making examples less expressive.

Including the check `isTRUE(getOption('knitr.in.progress'))` in the knit_print-methods is a potential solution.

**Comment by PolMine** [comment]
Dear Andreas,

I just ran `pkgdown::build_site()` for the polmineR package, and the result looks fine. There are warnings, but they do not result from this issue, so I think it has been solved unreportedly. 

Kind regards, Andreas
