### ISSUE TITLE
use()-Method | verbose parameter doesn't do much?

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#47]
` .message(sprintf("activating corpus: %s", corpus))` isn't affected by verbose = FALSE but probably should be given the parameter description.

**Comment by PolMine** [comment]
I'll take care of it.

**Comment by PolMine** [comment]
Thanks again for raising the issue. Solving this has been obvious and easy, we just need to pass the argument `verbose` into the auxiliary `.message`-function that produces the messages. The bug fix is included in the new development version of polmineR.

On this occasion, I took care that corpora that are activated are reported in capital letters. I had been thinking for a while that it is quite confusing that corpora show up in lowercase letters in the output message of the `use()`-function, but then you consistently need to use the uppercase version of the corpus name...

**Comment by ChristophLeonhardt** [comment]
The output in capital letters does makes a lot of sense indeed.
