### ISSUE TITLE
kwic()-Method: Too large window throws error if window reaches past max cpos of corpus

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#48]
```{r}
last <- partition("GERMAPARL", date = "2016-12-16", role = "presidency")
kwic(last, "Sitzung")
```

"Sitzung" as the forth last token of GermaParl and the standard window of five.

**Comment by PolMine** [comment]
Thanks for raising the issue. A new check in the `context()`-method that is called by `kwic()`addresses the issue. The bug will not occurr in polmineR v0.7.10.9008 that I am about to push to the development branch.
