### ISSUE TITLE
highlight | using highlight with kwic doubles displayed s_attributes in viewer output

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#49]
```{r}
kwic("MIGPARL", query = "Islam", positivelist = "Konferenz", meta = "speaker") %>% 
  highlight(list(yellow = "Konferenz", lightgreen = c("Junge", "Jungen")))
```
output:

| speaker        	| speaker.1      	| left       	| node  	| right                	|
|----------------	|----------------	|------------	|-------	|----------------------	|
| Max Mustermann 	| Max Mustermann 	| five words 	| Islam 	| Konferenz more words 	|

**Comment by PolMine** [comment]
Thanks: The next version on the dev branch solves the issue with applying `unique()` on the s_attributes that serve as metadata.
