### ISSUE TITLE
as.speeches method - speakerFlatList not found

### ISSUE THREAD

**Issue by simongehlhar** [PolMine/polmineR#50]
Method returns error "speakerFlatList" not found and aborts. Only occurs in newer Versions. CRAN-Release works fine...

**Comment by PolMine** [comment]
Can you please include a full reproducible example?

**Comment by simongehlhar** [comment]
[1] polmineR_0.7.10.9006

```
corpus <- "GERMAPARLMINI"
k <- 100
language <- "de"
```
`speeches <- as.speeches(.Object = corpus, s_attribute_date = "date", s_attribute_name = "speaker")
`

> ... generating partitions by date
... getting matrix with regions for s-attribute:  date
... generating the partitions
... generating speeches
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 01s
... generating names

some 25+ error like below follow:
> no non-missing arguments to min; returning Infno non-missing arguments to max; returning -Infno non-missing arguments to min;

but the main error seems to be this:
> returning -InfError in as.speeches(.Object = corpus, s_attribute_date = "date", s_attribute_name = "speaker") : 
  object 'speakerFlatList' not found

I switched from dev to master branch but the problem still exists. Like I said before: the cran release works just fine.

**Comment by simongehlhar** [comment]
Never mind. Updated cwbtools and RccpCWB and now it works like a charm!

**Comment by PolMine** [comment]
Dear Simon,
thanks for reporting the issue. Admittedly, I do not know why updating RcppCWB and cwbtools solved the issue. Moving away from lowerCamelCase, 'speakerFlatList' should be 'speaker_list'. So this is corrected in the new development version.
Andreas
