### ISSUE TITLE
features-method: log likelihood undocumented

### ISSUE THREAD

**Issue by Studentenfutter** [PolMine/polmineR#52]
?features mentions the possibillity to use log likelihood as a statistical method, however this feature is not documented and only usable by using method = "ll".

**Comment by PolMine** [comment]
Good point. The new polmineR version 0.7.10.9009 on the development branch includes a very substantial rework of the `ll()`-method. A thorough explanation was a particular aim, but the new push also tries to ensure that the method is available more consistently. Maybe you want to have a look at the documentation (?ll), and the examples that are now included?
Andreas
