### ISSUE TITLE
Windows installation fails: Error : object 'mccollect' is not exported by 'namespace:parallel'

### ISSUE THREAD

**Issue by grenwi** [PolMine/polmineR#54]
Installation on Windows 10 failswith this error

```
Error : object 'mccollect' is not exported by 'namespace:parallel'
ERROR: lazy loading failed for package 'polmineR'
* removing 'C:/Users/rioreiser/Documents/R/win-library/3.5/polmineR'
In R CMD INSTALL
Installation failed: Command failed (1)
```

Presumably, 'mccollect' does not exist in the Windows Version of the parallel package?

**Comment by PolMine** [comment]
That's it: mccollect is not available on Windows. But it is not needed in the recent version, so I dropped the import. Maybe try again, hope it works now.

**Comment by PolMine** [comment]
As far as I can see, omitting to import mccollect from the parallel-package solved the problem, so I will close this issue.
