### ISSUE TITLE
as.speeches method crashes on partition objects

### ISSUE THREAD

**Issue by simongehlhar** [PolMine/polmineR#57]
The as.speeches method crashes when the object is a partition. Please note that it works if the partition was created from the "GermaParl"-Corpus. But on any other corpora it will crash:
```
foo <- partition("HOUSEOFCOMMONS", party=c("UKIP", "SDP"))
speeches <- as.speeches(.Object = foo, s_attribute_date = "date", s_attribute_name = "speaker")
```
this will result in the following error message:
```
... generating partitions by date
... getting values for s-attribute  date
... number of partitions to be generated:  181
Error in validObject(.Object) : 
  invalid class “partition” object: invalid object for slot "name" in class "partition": got class "NULL", should be or extend class "character"
```
Using the method on the "HOUSEOFCOMMONS"-Corpora works just fine.

**Comment by PolMine** [comment]
I just checked that the example provided by Simon works now. Works nicely now, so I will close the issue.
(Just one remark: Calls to the blapply method are much harder to understand than they should. I like the idea to have a method to iterate over lists, and partition_bundle objects with optional progress bars and multicore support, but in the long run, the solution should be different from what we have now...)
