### ISSUE TITLE
calculating differences in speech patterns between parliamentary groups, calculation stops 

### ISSUE THREAD

**Issue by svenjakopyciok** [PolMine/polmineR#59]
When calculating differences in speech patterns between parliamentary groups, the calculation stops after (usually) two parliamentary groups: 

queries <- c("Flüchtlinge", "Asylbewerber", "Asylsuchende", "Geflüchtete", "Migranten")

par(
  mar = c(8,5,2,2), # Anpassung Ränder => Beschriftung vollständig sichtbar
  mfrow = c(2,2) # Ausgabe verschiedener Balkendiagramme in ein Feld
)

for (pg in c("CDU/CSU", "GRUENE", "SPD", "LINKE")){
  dt <- partition("GERMAPARL", parliamentary_group = pg, year = 2016) %>%
    count(p, query = queries)
  barplot(
    height = dt$freq * 100000, names.arg = dt$query, # Beschriftung mit Suchbegriffen
    las = 2, # Drehung Beschriftung um 90 Grad für Lesbarkeit
    main = pg,
    xlab = "Frequenz der Begriffe (pro 100.000 Token)",
    ylim = c(0, 50) # einheitliche Skalierung y-Achse für Vergleichbarkeit
  )
}

**Comment by PolMine** [comment]
Dear Svenja, 

there is an issue I had myself a while ago with loops that create visualisations, and first I thought, you have delivered a reproducable example. But maybe there is a different issue here. As I see it, you use the pipe operator of the magrittr package `%>%`, but the call of the `count()`-method does not omit the first object passed into from the previous function call. So the "p," is wrong. This is the code that works nicely for me, please let me know whether it does for you:

```r
library(polmineR)
library(magrittr)
use("GermaParl")

queries <- c("Flüchtlinge", "Asylbewerber", "Asylsuchende", "Geflüchtete", "Migranten")

par(
  mar = c(8,5,2,2), # Anpassung Ränder => Beschriftung vollständig sichtbar
  mfrow = c(2,2) # Ausgabe verschiedener Balkendiagramme in ein Feld
)

for (pg in c("CDU/CSU", "GRUENE", "SPD", "LINKE")){
  dt <- partition("GERMAPARL", parliamentary_group = pg, year = 2016) %>%
    count(query = queries)
  barplot(
    height = dt$freq * 100000, names.arg = dt$query, # Beschriftung mit Suchbegriffen
    las = 2, # Drehung Beschriftung um 90 Grad für Lesbarkeit
    main = pg,
    xlab = "Frequenz der Begriffe (pro 100.000 Token)",
    ylim = c(0, 50) # einheitliche Skalierung y-Achse für Vergleichbarkeit
  )
}
```

Andreas

**Comment by PolMine** [comment]
Dear Svenja,

as I still think that the solution I suggested does the job, I hope it is ok that I close the issue. Please let us know if we did not address your point adequately.

Kind regards
Andreas
