### ISSUE TITLE
Shiny | Partition creation crashes when p_attribute which is listed but not available is chosen

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#60]
When using polmineR::polmineR() with GermaParlMini and choosing p_attribute "lemma" when creating a partition, the following error occurs: 

Warning: Error in .local: all(p_attribute %in% p_attributes(.Object)) is not TRUE

**Comment by ablaette** [comment]
Perfectly right, it is necessary to update the available p-attributes, whenever a new corpus is chosen. The same is true for cooccurrences, and counting, and I hope/think that I have implemented things appropriately now. That's available in a new version of polmineR I am about to push to the dev branch. Would you mind having a look?

**Comment by ChristophLeonhardt** [comment]
I am not sure if this is connected with your fix, but now I cannot create any partitions. 

Example: I am trying to create a partition in the shiny environment:

Corpus: GermaParlMini
Name: unnamed (doesn’t matter)
s_attribute: party
party: SPD
p_attribute: word
regex = FALSE
xml = flat

This crashes the shiny interface. The feedback of the R console is: 

> Warning: Error in .local: Corpus 'unnamed' is not available.

**Comment by ablaette** [comment]
Admittedly, there has been an unintended side-effect of my effort to create automatic updates for the p-attributes when a new corpus is selected. Hope it works now.
