### ISSUE TITLE
Shiny | Dispersion crashes, all the time 

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#62]
Dispersion crashes all the time, both with default options and when changing  things around. Tested with polmineR::polmineR(), GermaParlMini and the query "Herr".  The error is always:

`Error in .cl_str2id(corpus = corpus, p_attribute = p_attribute, str = str,  : 
  Expecting a single string value: [type=NULL; extent=0].
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 00s
Warning: Error in check_cpos: all corpus positions (cpos) need to be <= attribute size, not TRUE
`

**Comment by ablaette** [comment]
This substantial malfunction of dispersion in the shiny app is now solved, with polmineR v0.7.11.9027 (on the dev branch, `devtools::install_github("PolMine/polmineR", ref = "dev")`. Having worked on this part of the shiny app anyway, more functionality of the `dispersion()`-method is exposed than before (usage of cqp syntax, for instance). 

I am fairly sure that this part of the shiny app is not yet robust and that we will see more specific issues. But as this general issue is addressed, I will close it.
