### ISSUE TITLE
get_token_stream for partition_bundle

### ISSUE THREAD

**Issue by PolMine** [PolMine/polmineR#63]
This is missing!

**Comment by ablaette** [comment]
I have now started to include a basic implementation of this feature in the recent development version. Interestingly, the following sample code results in an outright crash.

```r
pb <- partition_bundle("REUTERS", s_attribute = "id")
ts_list <- get_token_stream(pb, progress = FALSE, collapse = TRUE)
```

**Comment by ablaette** [comment]
Having solved an issue with the `as.VCorpus()`-method, the problem with the `collapse` argument is solved, too. Note that the collapse argument needs to be a length-one character vector.

```r
pb <- partition_bundle("REUTERS", s_attribute = "id")
ts_list <- get_token_stream(pb, progress = FALSE, collapse = " ")
```
