### ISSUE TITLE
Document get_token_stream()-methods

### ISSUE THREAD

**Issue by PolMine** [PolMine/polmineR#65]
The documentation for the method is fairly rudimentary: Document the individual methods!

**Comment by ablaette** [comment]
The documentation of `get_token_stream` has been thorougly worked and is available via the new polmineR version at the dev branch. Note that I also drastically improved the test coverage of the method, see the report at [codecov](https://codecov.io/gh/PolMine/polmineR/src/dev/R/token_stream.R).
