### ISSUE TITLE
Files in temporary registry directory disappear when calling devtools::document()

### ISSUE THREAD

**Issue by PolMine** [PolMine/polmineR#68]
The polmineR packages uses a temporary registry directory, but the files stored there disappear when calling devtools::document() in a session:

```r
library(polmineR)
use("polmineR")
list.files(registry())

devtools::document("~/Lab/github/polmineR")
list.files(registry())

use("polmineR")
list.files(registry())
```
If you know about what devtools does, this is not a big problem, but the behaviour is fairly confusing.

**Comment by ablaette** [comment]
This is just a quick idea what might happen. My guess would be that `devtools::document`detaches the package that is documented. This would mean that the `.onDetach()`-function would be called during the documentation procedure, which deletes the temporary registry directory.

```r
.onDetach <- function(libpath){
  unlink(registry(), recursive = TRUE, force = TRUE)
  unlink(data_dir(), recursive = TRUE, force = TRUE)
}
```

There is still the mystery, why `devtools::document` wouldn't attach the package again. To be continued...

**Comment by PolMine** [comment]
Let me tell (myself or anybody interested) the quirky story why registry files are gone after calling `devtools::document()`. Contradicting my previous suspicion, the package is attached again after calling `devtools::document()`. But this is what happens...

Indeed, temporary registry files (in the temporary directory you get by calling `registry()`) are deleted when calling `devtools::document()`. But the files are only gone when re-documenting the polmineR package. The files are still there if another package is documented. The temporary directory remains intact, and indeed the "polmineR_registry" subdirectory of the tempdir is there again. It is just the files that are gone.

The `devtools::document()` function is just a wrapper for `roxygen2::roxygenise()`, so this needs to be examined.

Within `roxygen2::roxygenise()`, this is the line that causes the issue, i.e. after `pkgload::load_all()`, the registry files are gone.

```r
pkgload::load_all(path, helpers = FALSE, attach_testthat = FALSE)$env`
```

Within this function, the package is unloaded (`unload(package, quiet = quiet)`). In the case of the polmineR package, this triggers a call of the `.onDetach()` function in the zzz.R file, and this is when the temporary registry directory is deleted (`unlink(registry(), recursive = TRUE, force = TRUE)`)

After unloading the package, the `pkgload::load_all()` function calls `run_pkg_hook(package, "load")` (and `run_pkg_hook(package, "attach"`). The `.onLoad()` function is executed, and this is why the temporary registry directory is there again.

However, the package is assumed to be an installed package, and the "extdata" folder is wrapped into the "inst" folder. However, when the package is not yet installed, the "extadata" folder is within the "inst" folder. 

So the the solution to check the possibility within `.onAttach()` that "extdata" is within an inst folder. This is my solution:

```r
  pkg_registry_dir_alternatives <- c(
    file.path(normalizePath(libname, winslash = "/"), pkgname, "extdata", "cwb", "registry", fsep = "/"),
    file.path(normalizePath(libname, winslash = "/"), pkgname, "inst", "extdata", "cwb", "registry", fsep = "/")
  )
  pkg_registry_dir <- pkg_registry_dir_alternatives[dir.exists(pkg_registry_dir_alternatives)]
```

As far as I can see this solves the issue, so I will close it. Note that upon having a fresh look at `.onAttach()`, `.onLoad()` and `.onDetach()` I noted that options defined by the polmineR package will survive unloading the package. To unload the package cleanly, I added this line to the `.onDetach()` function:

```r
do.call(options, args = sapply(grep("polmineR\\.", names(options()), value = TRUE), function(x) NULL))
```

It will remove all options starting with "polmineR.".
