### ISSUE TITLE
count()-method does not find named entities

### ISSUE THREAD

**Issue by PolMine** [PolMine/polmineR#69]
It is somewhat strange: Using the `kwic()`-method to inspect the context of a tagged named entity works:

```r
kwic("GERMAPARLMINI", query = '<ne> []* </ne>', cqp = TRUE)
```
But using the `count()`-method does not show results:

```r
count("GERMAPARLMINI", query = '<ne> []* </ne>', cqp = TRUE)
```

**Comment by ablaette** [comment]
Using a sample annotation generated GermaNER (as described in the vignette of the - new - [GermaNER R package](https://github.com/PolMine/GermaNER)), I cannot reproduce the result. Everything works as intended. So no matter what was wrong, it's ok now.
