### ISSUE TITLE
show()/round()-method throws error for textstat-class object

### ISSUE THREAD

**Issue by PolMine** [PolMine/polmineR#71]
See the following example:
```r
library(polmineR)
y <- new("textstat")
show(y)
```
Fehler in round(dt, digits = digits) : 
  Nicht-numerisches Argument für mathematische Funktion

**Comment by ablaette** [comment]
Indeed, there is nothing to show, when an object has just been initialized. But the error message is not very informative. Now, the `format()`-method, the worker behind `show` for textstat objects checks whether there is a `data.table` in the `stat` slot and tells users 'No data.table in slot stat of the object - cannot show output.', if not.

As I think this is a sufficient solution, I will close the issue.
