### ISSUE TITLE
Feature Request: onload-Message for use()-Method

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#72]
Wouldn't it be beneficial if while loading a corpus via use() a onload message would appear indicating the corpus version/build date etc.? Maybe grabbing this information from the info.md would make sense, as in polmineR::registry_get_info().

**Comment by ablaette** [comment]
I really do like this idea, but I think it would still be somewhat premature to pursue it. Reporting the corpus version/build date by default requires that the data is available in a standardised fashion, either in the info.md file, or in the registry file.

My argument against the info.md file is that it is a text file, so you would need to use regular expressions to get the information out of the file, which is not perfectly reliable unless the text file is highly standardised. 

My argument against the registry file is that it is stored at a seperate location than the data, and I can imagine situations when the registry file is out of touch with the data. The advantage of the registry file: It is highly standardised, and adding new corpus properties is possible.
See the [CWB Encoding Tutorial](http://cwb.sourceforge.net/files/CWB_Encoding_Tutorial.pdf), page 20.

Would be great to hear your opinion.

**Comment by ChristophLeonhardt** [comment]
I agree. This depends entirely on having a standardized way of recoding the corpus version and a robust way to access this information. But I think that this is something we will have to look at anyway to ensure reproducible research. 

If I understand correctly, when writing about the registry file, you suggest the possibility to add the build date/corpus version as a corpus property in the registry file itself, such as:

> ##:: build_date = "2019-10-02"    

I am not sure under which circumstances the registry file would be out of touch with the actual data (apart from patching an existing corpus). Other than that, I think that this would be a proper solution to establish a robust practice of versioning corpora which wouldn't add any procedural overhead as you create the file anyway.

One solution might also involve the automatic creation of an info file as part of the corpus creation process which might then be stored alongside the data. This would be true for both the info.md and the .info file which can be linked in the registry file.

**Comment by ablaette** [comment]
I think we should go for an evaluation of the properties "version" and "build_date" in the registry file. If you handle your data really badly, there might be a confusion whether a registry file is really the correct registry file in a data directory. But it really should not happen.

My suggestion is to keep the issue open, to address it later on. I started to work on a CRAN release of cwbtools. That package includes some consolidated functionality to evaluate and manipulate registry files. Before reimplementing this in polmineR, I think the better way is to use cwbtools available as a dependency easily available via CRAN.

**Comment by PolMine** [comment]
Showing the version number and build date of a corpus when calling `use()` if the respective information is available in the registry file is now implemented (experimentally).

The GERMAPARLMINI corpus includes the respective definitions of the corpus properties. So when you run this ... 

```r
library(polmineR)
use("polmineR")
```
you shoud see:

... activating corpus: GERMAPARLMINI (version: 0.0.1 | build date: 2019-02-23)
... activating corpus: REUTERS

The logical next step would be to include the version and the build date in the table returned when calling `corpus()`.

**Comment by ChristophLeonhardt** [comment]
I do like this solution because it allows the storage of this information alongside the data itself. Using the registry file certainly is the most sustainable solution here. To go along with that, the possibility to manipulate the registry file during corpus creation would be beneficial. I created an issue for this for the `cwbtools` package: https://github.com/PolMine/cwbtools/issues/13
