### ISSUE TITLE
kwic() for partition_bundle

### ISSUE THREAD

**Issue by jkrss** [PolMine/polmineR#73]
Hi
is there any method to use kwic() for partition_bundles? 

This is my current work flow:

```
corpus <- partition_bundle("SBZ", s_attribute = "text_id", progress = TRUE)
corpus.sample = sample(corpus, 10000)
corpus.sample.lemma <- pblapply(corpus.sample@objects, function(x) get_token_stream(x, p_attribute = "lemma"))
```

 `corpus.sample.lemma` is the basis for calculating vector space representations. Later on I need concordances to evaluate the vector space. Hence the need for kwic() on partition_bundles (especially since I draw a sample of 10000 texts and I need the concordances come from this sample and not from the larger corpus.

`kwic = kwic(corpus.sample, "Ausländer", left = 10, right = 10, p_attribute = "lemma") %>% as.data.frame()` throws the following error:

> Fehler in (function (classes, fdef, mtable)  : 
>   unable to find an inherited method for function ‘kwic’ for signature ‘"partition_bundle"’
> 

Thanks for helping me out!

**Comment by ablaette** [comment]
Interesting question. I had not thought that a `kwic()`-method for `partition_bundle` objects would be considered useful. In your case, you might proceed as follows, using the `subset()`-method that is available for `kwic`objects. (Code is not tested!)

```r
corpus <- partition_bundle("SBZ", s_attribute = "text_id", progress = TRUE)
corpus.sample = sample(corpus, 10000)

ids <- s_attributes(corpus.sample, "text_id")
k <- kwic("SBZ", query = "YOURQUERY", meta = "text_id")
k_sample <- subset(k, text_id %in% ids)
```

Another option would be to merge the sample into one partition:

```r
p <- merge(corpus.sample)
kwic(p, query = "YOURQUERY")
```

Then you would only have concordances left that occurr in your sample. 

Implementing a kwic,partition_bundle-method would not be difficult, but I have my doubts that it is easy to make it more efficient than the two approaches just described.

Let me know whether it works!

**Comment by jkrss** [comment]
The first option works perfectly well. Merging into one partition works, too - but the kwic is produced for the larger corpus anyway (kwic(p, query = "YOURQUERY")).

Thanks for helping me out!

**Comment by ablaette** [comment]
Reconsidering our previous (March) conversation, the easy way out would be that I was apparantly able to offer a solution for your problem. But even if your scenario could be addressed with the functionality that is already there, there is something else on my mind ...

Imagine you have created subcorpora based on combinations of s-attributes, and you want to see the names of the subcorpora in your kwic output. 

A real scenario would be that you create a bundle with speeches, which are not mapped by s-attributes, but a virtual subdivision of the data. I think this is a real case when you would be glad to have a `kwic,subcorpus_bundle`-method, to be able to merge the `kwic_bundle`-object into a single `kwic` object, and to have the names of the subcorpora as an additional meta information.

Implemementing this will entail having a look at the whole system of methods surrounding the `kwic` and the `context` classos, I cannot not implement this right away. If I receive feedback in the meantime, I don`t mind.-

**Comment by PolMine** [comment]
The issue whether we might want to have a `kwic()` method for `partition_bundle` / `subcorpus_bundle` objects has been open for a while. Now I have implemented the method, because the scenario I had in mind when writing my last comment on the issue has become relevant: If we want to link a `kwic` class object with a `partition_bundle` with speeches (there is no s-attribute 'speech'), we need an id for linking. See this example I also use in the expanded documentation (polmineR v0.8.0.9005 from dev branch required).

```r
gparl_2009_11_10_speeches <- corpus("GERMAPARLMINI") %>%
  subset(date == "2009-11-10") %>%
  as.speeches(s_attribute_name = "speaker", progress = FALSE, verbose = FALSE)
k <- kwic(gparl_2009_11_10_speeches, query = "Integration")
```

If you inspect k, you will see a column 'subcorpus_name' which can be used as a link to the original `subcorpus`/`partition`.
