### ISSUE TITLE
merge-method for subcorpus-objects

### ISSUE THREAD

**Issue by ablaette** [PolMine/polmineR#76]
Theoretically, a  subcorpus A and a subcorpus B that results from splitting and merging subcorpus B should be identical. But this is not the case at this stage.

```r
library(polmineR)
use("polmineR")

A <- corpus("GERMAPARLMINI") %>%
  subset(interjection == "speech") %>%
  split(s_attribute = "speaker") %>%
  merge() %>%
  as("subcorpus") %>%
  as("plpr_subcorpus")

B <- corpus("GERMAPARLMINI") %>% subset(interjection == "speech")
```
The order of regions in subcorpus B is mixed up (left corpus positions are not ordered in an in creasing manner), and A@cpos has dimnames, whereas B@cpos has not. So the `merge()`-method for `partition_bundle`-objects that is inherited for `subcorpus_bundle`-objects is not ideal at all, and a rewritten `merge()`-method for `subcorpus_bundle`-objects should solve the problem.

**Comment by PolMine** [comment]
There is now a `merge()`-method for the `subcorpus_class`. It extends the method for the `partition_class`. The inconsistencies noted above are addressed. This code serves as a respective check:

```r
library(polmineR)
use("polmineR")

A <- corpus("GERMAPARLMINI") %>%
  subset(interjection == "speech") %>%
  split(s_attribute = "speaker") %>%
  merge()

B <- corpus("GERMAPARLMINI") %>% 
  subset(interjection == "speech")

B@s_attributes <- list()
B@s_attribute_strucs <- "speaker"

identical(A, B)
```
