### ISSUE TITLE
label | Feature Request | Conveniently label a list of kwic objects 

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#80]
Let's assume I have a List of KWIC objects called "war_kwic" I produced as follows:

```{r}
library(polmineR) 
use("GermaParl")

dict <- list('".*[Kk]onflikt.*"', '".*[Kk]rieg.*"')

war_kwic <-lapply(dict, 
       function(Q) {
         x <- context("GERMAPARL", query = Q, positivelist = c("Irak", "Afghanistan"), cqp = TRUE, left = 15, right = 15) %>%
           kwic()
       }         
  )

```

How would I label the kwics in the war_kwic list?

```{r}
for (k in war_kwic) {
  label(k, js = "Handsontable")
  readline()
}
```

This does the job, I assume. You can label the items, press "Done". The interactive viewer overlay disappears and then you can press "Enter" to continue with the next KWIC object. However, it could be more intuitive if label can take a list as input and pressing "Done" continues with the next object. 

Alternatively: Is there a easy way to collapse all the kwic objects in the list to one object I can label?

**Comment by PolMine** [comment]
Good point. The most recent development version of polmineR (0.7.11.9022) involves some refactoring of the `kwic`class: The `table`-slot now expects a `data.table`, so we do not need a `labels` class slot object any more for reference semantics. This has been a precondition for making  merging a list of `kwic`-objects much easier. Having introduced a `kwic-bundle`-class and a `merge()`-method for that new class, this is possible now:

```r
reuters <- corpus("REUTERS")
queries <- c('"Saudi" "Arabia"', "oil", '"barrel.*"')

k <- lapply(queries, function(qu) kwic(reuters, query = qu)) %>%
  as.bundle() %>%
  merge()

annotations(k) <- list(name = "category", what = factor("a", levels = c("a", "b", "c")))
edit(k)
```
Documentation may not yet be perfect, but see the example `?kwic-class`.

**Comment by ChristophLeonhardt** [comment]
Yes, this is very much what I've been looking for.
