### ISSUE TITLE
Feature Request | context and kwic | different left and right values?

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#81]
In a situation in which someone would like to use positivelist and stop list to disambiguate hits, it might be reasonable to set a rather narrow window (+/- 3 or +/- 5) to grasp semantic context. However, manual validation which might follow eventually, is complicated by a narrow window. Here, it would be beneficial if the window of a context object which is called by kwic could be changed as follows: 

```{r}
x <- context("GERMAPARL", query = '".*[Kk]onflikt.*"', positivelist = c("Irak", "Afghanistan"), cqp = TRUE, left = 3, right = 3) 

kwic(x, left = 25, right = 25)
```

In this example, left and right are simply ignored by the kwic method, resulting in a kwic object with a left and right value of 3.

**Comment by ablaette** [comment]
Good point, I had been thinking about a similar scenario before. Experimentally, I added a new argument `extra` to the `enrich()`-method for kwic objects, which will add some context (polmineR dev branch, v0.7.11.9019).

For now, the extra output is only show shown, when you call `label()` with the rhandsontable widget. See the new example in the documentation object for the `label()`-method. This is the example.

```r
o <- kwic("REUTERS", query = "oil")
labels(o)[, "class" := factor(levels = c("a", "b", "c"))]
labels(o)[, "description" := ""]
o <- enrich(o, extra = 5L, table = TRUE)
label(o)
```
Maybe, we will line breaks for the kwic lines as they grow long, but that's the next step.

**Comment by ChristophLeonhardt** [comment]
This certainly does the trick.

**Comment by ablaette** [comment]
Coming back to our previous disussion, one might think that the extra context only works for labelling operations. It works, too, if you just want to look at the kwic lines.

```r
library(polmineR)
kwic("REUTERS", query = "oil") %>%
  enrich(extra = 5) %>%
  show()
```

So I will close the issue.-
