### ISSUE TITLE
highlight() method to show related words

### ISSUE THREAD

**Issue by KevinGlock** [PolMine/polmineR#83]
I want to highlight related words to a search word like this:

```r
library(polmineR)
use("GermaParl")

citizen <- kwic(
  "GERMAPARL",
   query = '"[Ss]taatsbürger.*"',
   left = 5, right = 5, cqp = TRUE,
   s_attributes = c("date", "speaker", "party")
)
citizen <- highlight(citizen, green = "doppelte")
view(citizen)
```

It works in the first step.
When I use the editor with view(citizen) there are no highlighted words. I can see only the html code <span> containing the colored token.
What's the problem about to see the actual color, not the code, like in UCSSR Chap. "KWIC-Analysen mit PolmineR" page 12?

**Comment by ablaette** [comment]
Please note that I edited your example slightly to make it work (missing quotation mark).

Using the `view()`-method to inspect a `kwic` object works as a matter of inheritance (from the `textstat` class). But it is an unconventional usage, the `show()`-method is intended be used. The `show()`-method is the method that is called when you just enter the name of an object at the prompt and hit enter. 

Understanding that it may not be quite clear that `view()` is not really intended to be used with `kwic` objects, the following warning will now (polmineR v0.7.11.9032 on the dev branch) be issued when use `view()`: 

"Using the 'view()'-method to inspect an object of the 'kwic'-class works, but the default method for kwic results is the 'show()'-method. You may see the column 'match_id', which is used internally, and raw html to highlight terms in the context of query matches."

I guess this will be sufficiently clear? So I will close the issue.
