### ISSUE TITLE
Call read on KWIC Object doesn't work anymore

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#84]
The example given in the UCSSR materials is as follows:

`
library(polmineR)
use("GermaParl")
bt2005 <- partition("GERMAPARL", year = 2005)
K <- kwic(bt2005, query = "Ausländer")
read(K, i = 1)
`

read(K, i = 1) throws an error:

```
read(K, i = 1)
Error: '.local' is defunct.
Use 'get_corpus' instead.
See help("Defunct") and help("polmineR-defunct"). 
13. stop(errorCondition(msg, old = fname, new = new, package = package, 
    class = "defunctError")) 
12. .Defunct(new = "get_corpus", package = "polmineR") 
11. .local(.Object, ...) 
10. corpus(.Object) 
9. corpus(.Object) 
8. tolower(corpus) 
7. file.path(registry, tolower(corpus)) 
6. readLines(file.path(registry, tolower(corpus))) 
5. stri_match_all_regex(readLines(file.path(registry, tolower(corpus))), 
    pattern = "^##::\\s*(.*?)\\s*=\\s*\"(.*?)\".*?$", omit_no_match = TRUE) 
4. registry_get_properties(corpus(.Object)) 
3. .local(.Object, ...) 
2. read(K, i = 1) 
1. read(K, i = 1) 
```

polmineR_0.7.11.9023 on R 3.6.0

**Comment by ablaette** [comment]
Gladfully, this was not too difficult. The default value for the argument `type` of the `read()`-method still made use of the `corpus()`-method to get the corpus ID, but this was replaced by a `get_corpus()`-method. With the new polmineR version at the dev branch, the following, somewhat edited code should work now.

```r
library(polmineR)
use("GermaParl")

k <- corpus("GERMAPARL") %>%
  subset(year == 2005) %>%
  kwic(query = "Ausländer")

read(k, i = 1)
```

On this occasion, I have edited the code somewhat to have more flexibility to read the fulltext for kwic lines selectively. So this works now.

```r
read(k, i = 5:7)
```
