### ISSUE TITLE
Call read doesn't work on partitions of certain corpora

### ISSUE THREAD

**Issue by simongehlhar** [PolMine/polmineR#85]
The read function does not work on partitions created from the tweedekamer-corpus.

`use("ParlSpeech")
p <- partition("TWEEDEKAMER", speaker="Volp", date="2015-09-01")
read(p)`

leads to

> Error in check_s_attribute(corpus = corpus, registry = registry, s_attribute = s_attribute) : 
  s_attribute needs to be a length 1 vector

polmineR: 0.7.11.9023 R: 3.5.0

**Comment by ChristophLeonhardt** [comment]
Odd. Your code works for me. polmineR: polmineR_0.7.11.9023

**Comment by ablaette** [comment]
Just to use the new workflow (subsetting corpora to get subcorpora), I have editted your example:

```r
library(polmineR)
use("ParlSpeech")

corpus("TWEEDEKAMER") %>%
  subset(speaker == "Volp") %>%
  subset(date == "2015-09-01") %>%
  read()
```

This works, so I cannot reproduce your example. Can you plrease retry, using the latest version of polmineR, and report what you see?
