### ISSUE TITLE
Feature Request | Sentence Boundary instead of left and right

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#87]
If you perform a cooccurrence analysis, the frequency of a term's cooccurrence with itself is striking. Often, the reason seems to be that the window size defined by "left" and "right" is wider than the sentence. In consequence, a term cooccurs with the same term which is mentioned in the previous (or following) sentence. This, however, doesn't necessarily convey semantic meaning. Here, a dynamic limitation of the window width to the sentence boundary would be handy. 

The same would be true when working with stop lists and positive lists, for example in KWIC. 

openNLP does have a sentence annotator but it is rather slow and needs rather different input.

**Comment by PolMine** [comment]
Good point. The ideal solution would possibly be to include an annotation of sentences e.g. Stanford CoreNLP
in the corpus from the outset. But for some reason, that may have been omitted. Indeed, there is a long history
of trials to add an annotation of sentences to an existing corpus. One of them is to use NLP/openNLP, see the 
examples for the `decode()`-method.

But if you have a corpus with an POS-annotation, there is a much faster way. This is a short example how you
may generate the data for encoding sentences using the POS-annotation of the TreeTagger.

We start by loading polmineR and activating GermaParl.

```r
library(polmineR)
use("GermaParl")
```

The we decode the positional attribute "pos". We will also need a vector with corpus positions with the 
same length.

```r
pos <- corpus("GERMAPARL") %>% get_token_stream(p_attribute = "pos")
cpos <- seq.int(from = 1L, to = length(word))
```

Now there is a sequence I use on some occasions in the polmineR package, a combination of
`cut()` and `split()`. It is much faster than what you can achieve with `data.table` implementation
or anything else I have tried. 

So we look up POS-annotations of sentence boundaries, generate a factor indicating sentences
by using `cut()`, split up the vector with corpus positions. The first and last positions of 
the vectors are the left and right corpus positions of sentences.

```r
sentence_end <- grep("\\$\\.", pos)
cpos_sentences <- cut(x = cpos, breaks = c(0L, sentence_end), right = TRUE)
y <- lapply(split(x = cpos, f = cpos_sentences), function(cpos) c(cpos[1L], cpos[length(cpos)]))
```

That is turned into a `data.frame` with the information that can be written to a corpus easily.

```r
m <- matrix(data = unlist(y), ncol = 2L, byrow = TRUE)
df <- data.frame(m)
colnames(df) <- c("cpos_left", "cpos_right")
df[["sentence"]] <- seq.int(from = 1L, to = nrow(df))
head(df)
```

Just to be sure, we check whether all words in the corpus are part of sentences.

```r
sum(dt_sent[["cpos_right"]] - dt_sent[["cpos_left"]]) + nrow(dt_sent)
```

And we can split up the token stream using our factor to see whether we have sentences indeed.

```r
word <- corpus("GERMAPARL") %>% get_token_stream(p_attribute = "word")
sentences <- split(x = word, f = cpos_sentences)
```

Works nicely, I think. The next step is to ensure that `context()`, `kwic()` and `cooccurrences()` can
make use of these sentence annotations.

**Comment by PolMine** [comment]
I just realised that the vector with corpus positions needs to be zero-based, so the code needs to be changed slightly. I add the call of `s_attribute_encode()` and a preliminary example how you might use the newly encoded structural attribute "s" for sentences.

```r
library(polmineR)
library(cwbtools)
use("GermaParl")

pos <- corpus("GERMAPARL") %>% get_token_stream(p_attribute = "pos")
cpos <- seq.int(from = 0L, to = length(pos) - 1L)

sentence_end <- grep("\\$\\.", pos)
cpos_sentences <- cut(x = cpos, breaks = c(0L, sentence_end), include.lowest = TRUE, right = FALSE)
y <- lapply(split(x = cpos, f = cpos_sentences), function(cpos) c(cpos[1L], cpos[length(cpos)]))

m <- matrix(data = unlist(y), ncol = 2L, byrow = TRUE)
df <- data.frame(m)
colnames(df) <- c("cpos_left", "cpos_right")
df[["sentence"]] <- seq.int(from = 0L, to = nrow(df) - 1L)
head(df)

s_attribute_encode(
  values = as.character(df[["sentence"]]),
  data_dir = cwbtools::registry_file_parse(corpus = "GERMAPARL")[["home"]],
  s_attribute = "s",
  corpus = "GERMAPARL",
  region_matrix = as.matrix(df[,c("cpos_left", "cpos_right")]),
  method = "R",
  registry_dir = registry(),
  encoding = cwbtools::registry_file_parse(corpus = "GERMAPARL")[["properties"]][["charset"]],
  delete = TRUE,
  verbose = TRUE
)

k <- kwic("GERMAPARL", query = "Integration", left = 30, right = 30, boundary = "s")
```

**Comment by PolMine** [comment]
To expand to the beginning and end of a sentence (provided you have created the annotation as described above), you may now use the following syntax.

```r
corpus("GERMAPARL") %>% context(query = "Integration", left = "s", right = "s") %>% kwic()
```

**Comment by ablaette** [comment]
Would be great to get some feedback, whether my suggested solution works. Then I will close the issue, an publish the recipe to create the sentence annotation as a blog post, so that the snippet is not lost.

**Comment by ChristophLeonhardt** [comment]
The solution you proposed does seem to do the trick initially. However, in the way it works now, the structural attribute „s“ is lost after a restart. 

Can you reproduce this behavior? Since it might have to do with s_attribute_encode, cwbtools version is: cwbtools_0.0.12.9004

**Comment by ablaette** [comment]
Yes, the behavior is not really odd for me: Making a new s-attribute available entails amending the registry file. But sind we have started to work with copies of the registry file in a temporary directory, it is the temporary file that is edited in my example. The information on the new attribute is lost when you restart R ... Good that you point this out, please let me think about a solution.

**Comment by PolMine** [comment]
To finally address the question how to ensure that a newly added s-attribute do not vanish from the registry (due to the temporary registry files polmineR uses) - the solution is quite simple: Write results to the original, not the temporary registry file. 

For corpora stored within packages, you can get the registry using the `registry()`-function, e.g. `registry(pkg = "polmineR")`. In the example above (augmenting GERMAPARL), this snippet needs to be inserted for the argument `registry` of the `s_attribute_encode()` function. I have edited the sample code accordingly.

In other scenarios, you might want to provide the system registry directory defined by the environment variable `CORPUS_REGISTRY` before polmineR starts. In the latest development version of polmineR, it keeps being accessible as an option (`getOption("polmineR.corpus_registry")`.

To avoid that closing this issue provokes that valuable code for sentence annotation is left to oblivion: I intend to save it as a vignette of the cwbtools package.

**Comment by PolMine** [comment]
So this is [link to the new preliminary vignette of the cwbtools package](https://github.com/PolMine/cwbtools/blob/dev/vignettes/sentences.Rmd) where the code for sentence annotation went. The further discussion should be conducted as an issue of the cwbtools package.
