### ISSUE TITLE
Cooccurrence() works with partition but not with subcorpus

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#88]
polmineR 0.7.11.9023

Reproducible code (which doesn't work but probably should):

`
cooc_germaparl <- subset("GERMAPARL", interjection = FALSE, year = 2014:2016)  %>%
  Cooccurrences(left = 10, right = 10, p_attribute = "word", stoplist = germaparl_noise)
`

**Comment by ablaette** [comment]
This is the example I used initially for testing - to reproduce your example, I did not have `germaparl_noise`.

```r
library(polmineR)
use("GermaParl")

cooc_germaparl <- corpus("GERMAPARL") %>%
  subset(year == 2014) %>%
  subset(interjection == FALSE) %>%
  Cooccurrences(left = 10, right = 10, p_attribute = "word")
```

The `Cooccurrences` class objects have a slot called `partition`, and incoming `subcorpus` class objects are not yet coerced to a `partition` object, which happens now.  For this purpose, I had to update the coerce method for `subcorpus` objects, which did not work ideally (i.e. threw an error).

In the long run, I am not sure I want to have a partition object to be stored within the Cooccurrences objects. But for the time being, the solution implemented works.

The bug fix is available with polmineR v0.7.11.9031 (dev branch).
