### ISSUE TITLE
No KWIC for subcorpus_bundle

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#89]
Title says it all, I guess:

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘kwic’ for signature ‘"subcorpus_bundle"’

polmineR_0.7.11.9024

Edit: Ah: It doesn't work for the partition_bundle-class either. 

It might well be that this is by design. I don't see any real necessity to perform a kwic-analysis on a partition_bundle. So you might close this issue if everything works as intended.

**Comment by ablaette** [comment]
In March, we had a conversation on this issue (no `kwic()`-method for `subcorpus_bundle`-objects), see issue #73. Although we came to a satisfactory solution at that time, I am still not totally sure that I want to reject the idea that a `kwic,subcorpus_bundle`-method is pointless. So I will keep #73 open, but close this one.
