### ISSUE TITLE
Different highlight output for partition

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#94]
Excuse the vague headline but its more of a subtle inconsistency than a bug. If I highlight context words in a KWIC output bases on a corpus, I can control colours, passing a vector.

```
kwic("REUTERS", query = "oil", positivelist = c("crude", "barrel")) %>%
  highlight(lightgreen = "crude", orange = "barrel") 
```

If I do the same for a KWIC analysis based on a partition, the colours aren't passed anymore.

```
partition("REUTERS", places = "usa") %>%
  kwic(query = "oil", positivelist = c("crude", "barrel")) %>%
  highlight(lightgreen = "crude", orange = "barrel") 
```

**Comment by ablaette** [comment]
The problem did exist, but by addressing issue #38, this (identical one) is solved, too.

Having slightly edited your example, this should work with polmineR 0.7.11.9030 available at the dev branch (`devtools::install_github("PolMine/polmineR", ref = "dev")`):

```r
library(polmineR)
corpus("REUTERS") %>%
  subset(places == "usa") %>%
  kwic(query = "oil", positivelist = c("crude", "barrel")) %>%
  highlight(lightgreen = "crude", orange = "barrel") 
```

I am confident that this is issue is solved, so I will close it. See explanations for issue #38 if you want to know about the problem you have come across.
