### ISSUE TITLE
Shiny| unable to find an inherited method for function ‘cooccurrences’ for signature ‘"Corpus"’  

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR#95]
In the shiny environment if I want to calculate cooccurrences for any query with either GermaParlMini or the Reuters corpus I get the error message: 

> "unable to find an inherited method for function ‘cooccurrences’ for signature ‘"Corpus"’"

polmineR_0.7.11.9030

**Comment by ChristophLeonhardt** [comment]
This is true for "count" as well.

**Comment by ablaette** [comment]
Making the cooccurrences functionality work again in the shiny app was not difficult. Please check the new polmineR version on the dev branch (v0.7.11.9032).

But I had some difficulty to understand and reproduce what the issue for 'count' might be. Can you give me more details on this, please?

**Comment by ChristophLeonhardt** [comment]
When I submitted the issue, besides 

> "unable to find an inherited method for function ‘cooccurrences’ for signature ‘"Corpus"’"

when calculating cooccurrences, I could trigger the error message

> "unable to find an inherited method for function ‘count’ for signature ‘"Corpus"’"

when using `count` in the Shiny environment. 

I cannot reproduce the problem now, using version 0.7.11.9038. So it was either fixed in the meantime or a temporary problem on my part. 

In any case, it doesn't seem to be an issue anymore, so feel free to close it.
