### ISSUE TITLE
enrich function does not preserve additional sAttributes

### ISSUE THREAD

**Issue by Studentenfutter** [PolMine/polmineR#96]
When applying the `enrich` function to an kwic-object, all additional s-Attribute columns of that kwic-object do not get carried over to the new object. Adjusting the `left`and `right` parameters of said kwic-object is working however.

```
x <- kwic("GERMAPARL", query = "Atomkraft", s_attributes = c("date", "parliamentary_group", "speaker", "role", "session"), left = 30, right = 30)
x <- enrich(x)
```

**Comment by ablaette** [comment]
Good point, this behavior is certinly unwanted. I rearranged the `enrich()` method, so that metadata / s-attributes are now added to the table *after* reconstructing the text. These are the examples I used.

```r
library(polmineR)
use("GermaParl")

x <- kwic(
  "GERMAPARL",
  query = "Atomkraft",
  s_attributes = c("date", "parliamentary_group"), 
  left = 30, right = 30
)
x
x <- enrich(x) #  does not kill existing s-attributes
x <- enrich(x, s_attribute = "speaker") 
x


kwic("GERMAPARL", query = "Integration", s_attributes = "date")

corpus("GERMAPARL") %>% kwic(query = "Integration") %>% enrich(s_attributes = "date")
```

Please let me now whether everything works as intended!

**Comment by Studentenfutter** [comment]
The `enrich()` seems to work but when using the newest dev version 0.7.11.9041 no sAttributes are attached to the kwic object and none are visible in the DataTable when using the `kwic()` example you provided - `kwic( "GERMAPARL",  query = "Atomkraft",  s_attributes = c("date", "parliamentary_group")` results in a DataTable containing only the columns `left`, `node` and `right`.

It seems that `kwic()` is broken for me.

SessionInfo: 
```
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] polmineR_0.7.11.9041
```

**Comment by Studentenfutter** [comment]
After further review, the error seemed to be related to my R setup and a possible Corpus registry error. After updating to the latest Version `0.7.11.9044` and restarting Rstudio and my machine everything seems to work flawless!

Thank you very much for the provided enriching pipeline method! I`ve tested the new tools extensively and did not run into any unintended problems. 

My error is resolved so I'll close this issue.
